## 1. 환경 설정

In [40]:
!pip install datasets
!pip install loralib
!pip install trl
!pip install accelerate
!pip install transformers
!pip install evaluate
!pip install nltk absl-py rouge_score

Requirement already satisfied: datasets in /opt/conda/lib/python3.12/site-packages (4.7.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.2.6)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from datasets) (2.3.0)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.12/site-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.12/site-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /opt/conda/lib/python3.12/site-packages (from datasets) (0.70.18)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.5.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /opt/conda/lib/python3.12/site-packages (from datasets) (1.6.0)
Requirement already satisfied: packaging in /opt/conda/lib/python3.12/site-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.12/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.1)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (4.14.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets) (2.4.0)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Requirement already satisfied: loralib in /opt/conda/lib/python3.12/site-packages (0.1.2)
Requirement already satisfied: trl in /opt/conda/lib/python3.12/site-packages (0.29.0)
Requirement already satisfied: accelerate>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from trl) (1.13.0)
Requirement already satisfied: datasets>=3.0.0 in /opt/conda/lib/python3.12/site-packages (from trl) (4.7.0)
Requirement already satisfied: packaging>20.0 in /opt/conda/lib/python3.12/site-packages (from trl) (25.0)
Requirement already satisfied: transformers>=4.56.2 in /opt/conda/lib/python3.12/site-packages (from trl) (5.3.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (2.2.6)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (7.0.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (2.7.1+cu118)
Requirement already satisfied: huggingface_hub>=0.21.0 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (1.6.0)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.12/site-packages (from accelerate>=1.4.0->trl) (0.7.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (3.13.1)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (23.0.1)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.4.0)
Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (2.3.0)
Requirement already satisfied: requests>=2.32.2 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (4.67.1)
Requirement already satisfied: xxhash in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /opt/conda/lib/python3.12/site-packages (from datasets>=3.0.0->trl) (0.70.18)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (2025.5.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (3.13.3)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1.0.0->datasets>=3.0.0->trl) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0.0->trl) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.4.1)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.14.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0.0->trl) (1.23.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (3.4.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.12/site-packages (from requests>=2.32.2->datasets>=3.0.0->trl) (2.4.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (11.8.86)
Requirement already satisfied: triton==3.3.1 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate>=1.4.0->trl) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate>=1.4.0->trl) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.12/site-packages (from transformers>=4.56.2->trl) (2026.2.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /opt/conda/lib/python3.12/site-packages (from transformers>=4.56.2->trl) (0.22.2)
Requirement already satisfied: sniffio>=1.1 in /opt/conda/lib/python3.12/site-packages (from anyio->httpx<1.0.0->datasets>=3.0.0->trl) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate>=1.4.0->trl) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas->datasets>=3.0.0->trl) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface_hub>=0.21.0->accelerate>=1.4.0->trl) (0.1.2)
Requirement already satisfied: accelerate in /opt/conda/lib/python3.12/site-packages (1.13.0)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.12/site-packages (from accelerate) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.12/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (2.7.1+cu118)
Requirement already satisfied: huggingface_hub>=0.21.0 in /opt/conda/lib/python3.12/site-packages (from accelerate) (1.6.0)
Requirement already satisfied: safetensors>=0.4.3 in /opt/conda/lib/python3.12/site-packages (from accelerate) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (3.13.1)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.5.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.3.2 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.4.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.28.1)
Requirement already satisfied: tqdm>=4.42.1 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typer in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/conda/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.14.0)
Requirement already satisfied: anyio in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (4.9.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (1.0.9)
Requirement already satisfied: idna in /opt/conda/lib/python3.12/site-packages (from httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: h11>=0.16 in /opt/conda/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface_hub>=0.21.0->accelerate) (0.16.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.6)

In [2]:
!git clone https://github.com/airobotlab/KoChatGPT
!cp -r KoChatGPT/colossalai_ChatGPT_230319/chatgpt chatgpt

fatal: destination path 'KoChatGPT' already exists and is not an empty directory.

In [3]:
# !rm -rf chatgpt

In [4]:
import os

modifications = [
    {
        "file": "chatgpt/trainer/callbacks/save_checkpoint.py",
        "changes": [
            {"line": 3, "old": "from chatgpt.trainer.strategies import ColossalAIStrategy, Strategy",
             "new": "from chatgpt.trainer.strategies import Strategy"},
            {"line": 71, "old": "only_rank0 = not isinstance(self.strategy, ColossalAIStrategy)",
             "new": "            only_rank0 = not isinstance(self.strategy)"},
        ],
    },
    {
        "file": "chatgpt/trainer/strategies/__init__.py",
        "changes": [
            {"line": 1, "old": "from .colossalai import ColossalAIStrategy", "new": ""},  # 삭제
            {"line": 5, "old": "__all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy', 'ColossalAIStrategy']",
             "new": "__all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy']"},
        ],
    },
    {
        "file": "chatgpt/dataset/reward_dataset.py",
        "changes": [
            {"line": 3, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ],
    },
    {
        "file": "chatgpt/trainer/strategies/__init__.py",
        "changes": [
            {"line": 8, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ]
    },
    {
        "file": "chatgpt/dataset/reward_dataset.py",
        "changes": [
            {"line": 8, "old": "from tqdm import tqdm", "new": "from tqdm.notebook import tqdm"},
        ]
    }
]

def modify_file(file_path, changes):
    """파일에서 지정된 줄을 찾아 내용을 수정하는 함수"""

    if not os.path.exists(file_path):
        print(f"⚠️ 파일이 존재하지 않습니다: {file_path}")
        return

    with open(file_path, "r", encoding="utf-8") as file:
        lines = file.readlines()

    modified = False

    for change in changes:
        line_index = change["line"]
        if 0 <= line_index < len(lines):
            if lines[line_index].strip() == change["old"]:
                lines[line_index] = change["new"] + "\n"
                modified = True
            else:
                print(f"⚠️ {file_path} 파일의 {change['line']}번째 줄이 예상과 다릅니다.")
                print(f"   예상: {change['old']}")
                print(f"   실제: {lines[line_index].strip()}")

    if modified:
        with open(file_path, "w", encoding="utf-8") as file:
            file.writelines(lines)
        print(f"✅ 수정 완료: {file_path}")
    else:
        print(f"⚠️ {file_path} 수정할 내용이 없습니다.")

for mod in modifications:
    modify_file(mod["file"], mod["changes"])

⚠️ chatgpt/trainer/callbacks/save_checkpoint.py 파일의 3번째 줄이 예상과 다릅니다.
   예상: from chatgpt.trainer.strategies import ColossalAIStrategy, Strategy
   실제: from chatgpt.trainer.strategies import Strategy
⚠️ chatgpt/trainer/callbacks/save_checkpoint.py 파일의 71번째 줄이 예상과 다릅니다.
   예상: only_rank0 = not isinstance(self.strategy, ColossalAIStrategy)
   실제: only_rank0 = not isinstance(self.strategy)
⚠️ chatgpt/trainer/callbacks/save_checkpoint.py 수정할 내용이 없습니다.
⚠️ chatgpt/trainer/strategies/__init__.py 파일의 1번째 줄이 예상과 다릅니다.
   예상: from .colossalai import ColossalAIStrategy
   실제:
⚠️ chatgpt/trainer/strategies/__init__.py 파일의 5번째 줄이 예상과 다릅니다.
   예상: __all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy', 'ColossalAIStrategy']
   실제: __all__ = ['Strategy', 'NaiveStrategy', 'DDPStrategy']
⚠️ chatgpt/trainer/strategies/__init__.py 수정할 내용이 없습니다.
⚠️ chatgpt/dataset/reward_dataset.py 파일의 3번째 줄이 예상과 다릅니다.
   예상: from tqdm import tqdm
   실제: from tqdm.notebook import tqdm
⚠️ chatgpt/dataset/reward_dataset.py 수정할 내용이 없습니다.
⚠️ chatgpt/trainer/strategies/__init__.py 수정할 내용이 없습니다.
⚠️ chatgpt/dataset/reward_dataset.py 파일의 8번째 줄이 예상과 다릅니다.
   예상: from tqdm import tqdm
   실제: class RewardDataset(Dataset):
⚠️ chatgpt/dataset/reward_dataset.py 수정할 내용이 없습니다.

In [5]:
%env CUDA_LAUNCH_BLOCKING=1

env: CUDA_LAUNCH_BLOCKING=1

In [38]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset

import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import PreTrainedTokenizerFast
from transformers import AutoModelForCausalLM, PreTrainedTokenizerFast

from transformers.models.gpt2.configuration_gpt2 import GPT2Config
from transformers.models.gpt2.modeling_gpt2 import GPT2Model

from chatgpt.dataset import RewardDataset
from chatgpt.models.base import RewardModel
from chatgpt.trainer.strategies import NaiveStrategy
from chatgpt.trainer.rm import RewardModelTrainer
from chatgpt.models.gpt import GPTActor, GPTCritic
from chatgpt.trainer import PPOTrainer

import evaluate

import pandas as pd
import numpy

from dataclasses import dataclass
from typing import Optional, Dict, Sequence

import copy
from copy import deepcopy
import random
from pathlib import Path
import json

import logging

print("Torch version:{}".format(torch.__version__)) # Torch version:1.12.1
print("Cuda version: {}".format(torch.version.cuda)) # Cuda version: 11.3
print("transformers version: {}".format(transformers.__version__)) # transformers 4.28.0
print("GPU 사용 가능여부: {}".format(torch.cuda.is_available()))

Torch version:2.7.1+cu118
Cuda version: 11.8
transformers version: 5.3.0
GPU 사용 가능여부: True

In [7]:
from dataclasses import dataclass, field

@dataclass
class Config:
    # ── 모델 설정 ──────────────────────────────────────────────
    model_name: str = "skt/kogpt2-base-v2"
    model_max_length: int = 512

    # 토크나이저 특수 토큰
    bos_token: str = "</s>"
    eos_token: str = "</s>"
    unk_token: str = "</s>"
    pad_token: str = "</s>"
    padding_side: str = "right"

    # ── 데이터 경로 ────────────────────────────────────────────
    data_path_1_SFT: str = "KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl"
    data_path_2_RM: str  = "KoChatGPT/data_kochatgpt/kochatgpt_2_RM.jsonl"
    data_path_3_PPO: str = "KoChatGPT/data_kochatgpt/kochatgpt_3_PPO.jsonl"

    # 정제된 데이터 경로 (EDA 후 생성)
    data_path_1_SFT_clean: str = "KoChatGPT/data_kochatgpt/kochatgpt_1_SFT_clean.jsonl"
    data_path_2_RM_clean: str  = "KoChatGPT/data_kochatgpt/kochatgpt_2_RM_clean.jsonl"

    # ── 모델 저장 경로 ─────────────────────────────────────────
    output_dir_SFT: str = "models/output_1_SFT"
    output_dir_RM: str  = "models/output_2_RM"
    output_dir_PPO: str = "models/output_3_PPO"
    sft_training_dir: str = "test"   # TrainingArguments output_dir

    # ── SFT 하이퍼파라미터 ─────────────────────────────────────
    sft_num_train_epochs: int = 1
    sft_per_device_train_batch_size: int = 8
    sft_per_device_eval_batch_size: int = 8
    sft_warmup_steps: int = 5
    sft_fp16: bool = True

    # ── Reward Model 하이퍼파라미터 ────────────────────────────
    rm_lr: float = 5e-5
    rm_batch_size: int = 4
    rm_max_epochs: int = 1
    rm_train_size: int = 1000          # train split 끝 인덱스
    rm_eval_size: int = 1200           # eval split 끝 인덱스
    rm_random_seed: int = 230319

    # ── PPO 하이퍼파라미터 ─────────────────────────────────────
    ppo_actor_lr: float = 5e-6
    ppo_critic_lr: float = 5e-6
    ppo_max_epochs: int = 1
    ppo_train_batch_size: int = 8
    ppo_max_length: int = 128
    ppo_temperature: float = 1.0
    ppo_top_k: int = 50
    ppo_num_episodes: int = 10
    ppo_max_timesteps: int = 3
    ppo_update_timesteps: int = 3
    ppo_tokenize_max_length: int = 96  # tokenize_fn 내부 max_length

    # ── 생성(Generation) 설정 ─────────────────────────────────
    gen_max_length: int = 128
    gen_num_beams: int = 4
    gen_repetition_penalty: float = 2.0
    gen_no_repeat_ngram_size: int = 4
    gen_eos_token_id: int = 375        # \n 토큰 ID
    gen_max_new_tokens: int = 64
    gen_top_k: int = 50

cfg = Config()
print("✅ Config 초기화 완료")
print(f"  model_name          : {cfg.model_name}")
print(f"  data_path_1_SFT     : {cfg.data_path_1_SFT}")
print(f"  output_dir_SFT      : {cfg.output_dir_SFT}")
print(f"  sft_num_train_epochs: {cfg.sft_num_train_epochs}")
print(f"  rm_lr               : {cfg.rm_lr}")
print(f"  ppo_actor_lr        : {cfg.ppo_actor_lr}")

✅ Config 초기화 완료
  model_name          : skt/kogpt2-base-v2
  data_path_1_SFT     : KoChatGPT/data_kochatgpt/kochatgpt_1_SFT.jsonl
  output_dir_SFT      : models/output_1_SFT
  sft_num_train_epochs: 1
  rm_lr               : 5e-05
  ppo_actor_lr        : 5e-06

## 2. 베이스 모델 및 데이터셋

In [8]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    cfg.model_name,
    bos_token=cfg.bos_token, eos_token=cfg.eos_token,
    unk_token=cfg.unk_token, pad_token=cfg.pad_token,
)
model = AutoModelForCausalLM.from_pretrained(cfg.model_name).to(device)

tokenizer.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [11]:
input_txt = "바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까."

In [12]:
tokens = tokenizer(input_txt).tokens()
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].numpy()

In [13]:
pd.options.display.max_columns = 40
pd.options.display.max_rows = 60
df = pd.DataFrame([tokens, input_ids[0]], index=["kogpt-2_tokens", "Input_IDs"])
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
kogpt-2_tokens,▁바람,도,▁없는,▁공중에,▁수직,의,▁파,문을,▁내,이며,▁고,요,히,▁떨어지는,▁오동,잎은,▁누,구의,▁발자,취,▁입,니까,.
Input_IDs,10891,7235,9712,49207,14438,8143,9203,9941,9094,9639,9065,8084,8811,21215,34769,19985,9669,10139,21626,8408,9241,23775,389

In [14]:
max_length=cfg.gen_max_length
input_ids = tokenizer(input_txt, return_tensors="pt")["input_ids"].to(device)
output_greedy = model.generate(input_ids, max_length=max_length, do_sample=False)
print(tokenizer.decode(output_greedy[0]))

model.safetensors:   0%|          | 0.00/513M [00:00<?, ?B/s]

바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취 입니까.'
"그렇다면 그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리요?"
"그건 무슨 소리

### 데이터셋 확인

In [19]:
with open(cfg.data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
print(len(list_data_dict))
list_data_dict[:3]

12000

[{'prompt': '불고기용 고기 한우에요?',
  'completion': "'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.",
  'tokens': 193},
 {'prompt': '쓰던 앱이 유료로 전환됐어',
  'completion': "'어떤 앱인지 모르기 때문에 정확한 답변을 드리기 어렵습니다. 하지만, 일반적으로 유료 전환된 앱은 기존 무료 앱에서 추가적인 기능이나 서비스를 제공하는 경우가 많습니다. 이 경우, 유료 전환 이전 가격이 매우 저렴하거나 무료인 경우가 많으므로, 앱을 계속 사용하려면 추가적인 비용을 지불해야 할 수 있습니다. 하지만, 유료 전환 이후에는 기존 사용자 또는 새로운 사용자 모두가 추가 기능과 높은 품질의 서비스를 이용할 수 있게 됩니다. 따라서, 앱 개발자는 유료 모델로 전환함으로써 앱의 수익을 증가시키고 더 나은 서비스를 제공할 수 있습니다.",
  'tokens': 288},
 {'prompt': '여친이랑 다툼',
  'completion': "'저는 인공지능이기 때문에 여친과의 다툼에 대해서는 조언을 드릴 수는 없습니다. 하지만 다투게 되면 상대방의 말을 경청하는 태도와 서로의 감정을 존중하는 것이 중요합니다. 논리적이고 차분한 대화를 통해 문제를 해결해보세요. 그리고 서로를 이해하고 서로의 의견을 수용하는 것이 중요합니다.",
  'tokens': 153}]

In [20]:
with open(cfg.data_path_2_RM, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
print(len(list_data_dict))
list_data_dict[:3]

10220

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?',
  'completion_0': 'Allow me to answer your question. I know that you are curious about me.',
  'completion_1': '번디는 다양한 인터뷰자들과 뉴스홍보 담당자들과의 면담 때 밝혔다.',
  'completion_2': '라이언에게 말했다.',
  'ranking': [2, 1, 0]},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?',
  'completion_0': '개포주공아파트는 다섯 단지로 이루어져 있습니다.',
  'completion_1': '이날 목송에서 구글상위노',
  'completion_2': '개포주공아파트는 총 27개 단지로 이루어져 있습니다.',
  'ranking': [2, 0, 1]},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?',
  'completion_0': 'The diameter of the Metallic domain is bigger than the Hyperonic domain.',
  'completion_1': '이 질문은 조금 불분명합니다. 김영삼 대통령이 후보 시절에 어떤 발언을 했고, 누가 그 발언을 문제삼았는지에 따라 답이 다를 수 있습니다.\\n\\n만약 김영삼 대통령이 후보 시절에 지역표심을 겨냥한 발언을 했다는 가정하에, 그 발언을 문제삼은 후보가 누구였는지를 대답하자면, 그 답은 이화선 당시 민주당 대통령 후보가 될 것입니다. 1992년 총선 때, 김영삼 대선후보는 "집값이 오른 노량진역 부근의 부동산 가격은 세월호 폭침 후 \\\'강남 도시재생\\\' 일환으로 상승했다"는 발언을 했습니다. 하지만 이화선 후보는 이 발언을 "전국적으로 경제적 발전이 이루어지지 않은 지방민의 마음을 멀리해지려는 무례한 발언"이라고 비판하며 문제삼았습니다.\\n\\n하지만, 이 질문을 답변하는 데 있어서 보다 명확한 정보가 있으면 답변을 보완할 수 있습니다.',
  'completion_2': '김영삼의 후보 시절에 지역표심을 겨냥한 발언은 대통령 당선 전까지 대한민국 정부가 추구하고 있는 민주주의 광범위하게 확립과 보수의 사상을 이어가는 데 있어 지역경제 발전과 공공서비스 신속 개선을 위해 합리적인 국가 정책에 따르는 방향성을 제시하고 있습니다.',
  'ranking': [1, 2, 0]}]

In [21]:
with open(cfg.data_path_3_PPO, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
print(len(list_data_dict))
list_data_dict[:3]

12000

[{'prompt': '번디는 자신이 탐정잡지, 범죄소설 그리고 성범죄 관련 실제 범죄 다큐멘터리들을 탐독했다고 누구에게 말했나?'},
 {'prompt': '개포주공아파트는 몇 단지로 이루어져 있나?'},
 {'prompt': '김영삼의 후보 시절 지역표심을 겨냥한 발언을 문제삼은 후보는?'}]

### 데이터셋 EDA

In [22]:
# ── 데이터셋 EDA ────────────────────────────────────────────────────────────
import pandas as pd, json, re

def load_jsonl(path):
    with open(path, 'r', encoding='utf-8-sig') as f:
        return json.load(f)

df_sft = pd.DataFrame(load_jsonl(cfg.data_path_1_SFT))
df_rm  = pd.DataFrame(load_jsonl(cfg.data_path_2_RM))
df_ppo = pd.DataFrame(load_jsonl(cfg.data_path_3_PPO))

print(f"[SFT]  rows={len(df_sft)}, cols={list(df_sft.columns)}")
print(f"[RM]   rows={len(df_rm)},  cols={list(df_rm.columns)}")
print(f"[PPO]  rows={len(df_ppo)}, cols={list(df_ppo.columns)}")

# 토큰 길이 분포
def token_len(text):
    return len(str(text).split())

for name, df, col in [("SFT prompt",  df_sft, "prompt"),
                       ("SFT completion", df_sft, "completion"),
                       ("PPO prompt",  df_ppo, "prompt")]:
    lens = df[col].apply(token_len)
    print(f"\n{name}: mean={lens.mean():.1f}, max={lens.max()}, min={lens.min()}, "
          f"std={lens.std():.1f}")

df_sft.head(3)

[SFT]  rows=12000, cols=['prompt', 'completion', 'tokens']
[RM]   rows=10220,  cols=['prompt', 'completion_0', 'completion_1', 'completion_2', 'ranking']
[PPO]  rows=12000, cols=['prompt']

SFT prompt: mean=5.5, max=68, min=0, std=3.3

SFT completion: mean=32.4, max=267, min=1, std=27.7

PPO prompt: mean=5.5, max=68, min=0, std=3.3

           prompt                                         completion  tokens
0   불고기용 고기 한우에요?  '저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하...     193
1  쓰던 앱이 유료로 전환됐어  '어떤 앱인지 모르기 때문에 정확한 답변을 드리기 어렵습니다. 하지만, 일반적으로 ...     288
2         여친이랑 다툼  '저는 인공지능이기 때문에 여친과의 다툼에 대해서는 조언을 드릴 수는 없습니다. 하...     153

### 데이터셋 정제

In [23]:
# ── 정제 기준 정의 ──────────────────────────────────────────────────────────
import re

def is_valid_sft(row):
    p, c = str(row.get('prompt', '')).strip(), str(row.get('completion', '')).strip()
    if len(p) < 5 or len(c) < 5:          # 너무 짧은 샘플 제거
        return False
    if len(c) > 500:                        # completion 과도하게 긴 샘플 제거
        return False
    if re.search(r'[\x00-\x08\x0b-\x0c\x0e-\x1f]', p + c):  # 제어문자 포함
        return False
    return True

df_sft_clean = df_sft[df_sft.apply(is_valid_sft, axis=1)].reset_index(drop=True)
print(f"SFT 정제 전: {len(df_sft)}  →  정제 후: {len(df_sft_clean)}")

# ── RM 데이터 정제 ──────────────────────────────────────────────────────────
def is_valid_rm(row):
    for col in ['completion_0', 'completion_1', 'completion_2']:
        c = str(row.get(col, '')).strip()
        if len(c) < 5 or len(c) > 600:
            return False
    return True

df_rm_clean = df_rm[df_rm.apply(is_valid_rm, axis=1)].reset_index(drop=True)
print(f"RM  정제 전: {len(df_rm)}  →  정제 후: {len(df_rm_clean)}")

# ── 정제된 파일 저장 ────────────────────────────────────────────────────────
import os, json

os.makedirs('KoChatGPT/data_kochatgpt', exist_ok=True)

clean_sft_path = 'KoChatGPT/data_kochatgpt/kochatgpt_1_SFT_clean.jsonl'
clean_rm_path  = 'KoChatGPT/data_kochatgpt/kochatgpt_2_RM_clean.jsonl'

with open(clean_sft_path, 'w', encoding='utf-8') as f:
    json.dump(df_sft_clean.to_dict('records'), f, ensure_ascii=False, indent=2)

with open(clean_rm_path, 'w', encoding='utf-8') as f:
    json.dump(df_rm_clean.to_dict('records'), f, ensure_ascii=False, indent=2)

print("정제된 데이터셋 저장 완료!")
print(f"  SFT clean → {clean_sft_path}")
print(f"  RM  clean → {clean_rm_path}")

SFT 정제 전: 12000  →  정제 후: 11553
RM  정제 전: 10220  →  정제 후: 9563
정제된 데이터셋 저장 완료!
  SFT clean → KoChatGPT/data_kochatgpt/kochatgpt_1_SFT_clean.jsonl
  RM  clean → KoChatGPT/data_kochatgpt/kochatgpt_2_RM_clean.jsonl

## 3. Supervised Fine-Tuning (SFT)

In [24]:
model = AutoModelForCausalLM.from_pretrained(cfg.model_name)
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    cfg.model_name,
    bos_token=cfg.bos_token, eos_token=cfg.eos_token,
    unk_token=cfg.unk_token, pad_token=cfg.pad_token,
    padding_side=cfg.padding_side,
    model_max_length=cfg.model_max_length,
)
print(tokenizer)

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

TokenizersBackend(name_or_path='skt/kogpt2-base-v2', vocab_size=51200, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'bos_token': '</s>', 'eos_token': '</s>', 'unk_token': '</s>', 'pad_token': '</s>'}, added_tokens_decoder={
	0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("<usr>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("<sys>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	5: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	6: AddedToken("<mask>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	7: AddedToken("<d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	8: AddedToken("</d>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	9: AddedToken("<unused0>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	10: AddedToken("<unused1>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	11: AddedToken("<unused2>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	12: AddedToken("<unused3>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	13: AddedToken("<unused4>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	14: AddedToken("<unused5>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	15: AddedToken("<unused6>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	16: AddedToken("<unused7>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	17: AddedToken("<unused8>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	18: AddedToken("<unused9>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	19: AddedToken("<unused10>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	20: AddedToken("<unused11>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	21: AddedToken("<unused12>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	22: AddedToken("<unused13>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	23: AddedToken("<unused14>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	24: AddedToken("<unused15>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	25: AddedToken("<unused16>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	26: AddedToken("<unused17>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	27: AddedToken("<unused18>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	28: AddedToken("<unused19>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	29: AddedToken("<unused20>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	30: AddedToken("<unused21>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	31: AddedToken("<unused22>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	32: AddedToken("<unused23>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	33: AddedToken("<unused24>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	34: AddedToken("<unused25>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	35: AddedToken("<unused26>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	36: AddedToken("<unused27>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	37: AddedToken("<unused28>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	38: AddedToken("<unused29>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	39: AddedToken("<unused30>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	40: AddedToken("<unused31>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	41: AddedToken("<unused32>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	42: AddedToken("<unused33>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	43: AddedToken("<unused34>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	44: AddedToken("<unused35>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	45: AddedToken("<unused36>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	46: AddedToken("<unused37>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	47: AddedToken("<unused38>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	48: AddedToken("<unused39>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	49: AddedToken("<unused40>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	50: AddedToken("<unused41>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	51: AddedToken("<unused42>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	52: AddedToken("<unused43>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	53: AddedToken("<unused44>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	54: AddedToken("<unused45>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	55: AddedToken("<unused46>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	56: AddedToken("<unused47>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	57: AddedToken("<unused48>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	58: AddedToken("<unused49>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	59: AddedToken("<unused50>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	60: AddedToken("<unused51>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	61: AddedToken("<unused52>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	62: AddedToken("<unused53>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	63: AddedToken("<unused54>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	64: AddedToken("<unused55>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	65: AddedToken("<unused56>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	66: AddedToken("<unused57>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	67: AddedToken("<unused58>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	68: AddedToken("<unused59>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	69: AddedToken("<unused60>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	70: AddedToken("<unused61>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	71: AddedToken("<unused62>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	72: AddedToken("<unused63>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	73: AddedToken("<unused64>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	74: AddedToken("<unused65>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	75: AddedToken("<unused66>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	76: AddedToken("<unused67>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	77: AddedToken("<unused68>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	78: AddedToken("<unused69>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	79: AddedToken("<unused70>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	80: AddedToken("<unused71>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	81: AddedToken("<unused72>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	82: AddedToken("<unused73>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	83: AddedToken("<unused74>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	84: AddedToken("<unused75>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	85: AddedToken("<unused76>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	86: AddedToken("<unused77>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	87: AddedToken("<unused78>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	88: AddedToken("<unused79>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	89: AddedToken("<unused80>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	90: AddedToken("<unused81>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	91: AddedToken("<unused82>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	92: AddedToken("<unused83>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	93: AddedToken("<unused84>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	94: AddedToken("<unused85>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	95: AddedToken("<unused86>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	96: AddedToken("<unused87>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	97: AddedToken("<unused88>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	98: AddedToken("<unused89>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	99: AddedToken("<unused90>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("<unused91>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("<unused92>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("<unused93>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("<unused94>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	104: AddedToken("<unused95>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	105: AddedToken("<unused96>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	106: AddedToken("<unused97>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	107: AddedToken("<unused98>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	108: AddedToken("<unused99>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	109: AddedToken(":-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	110: AddedToken(":)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	111: AddedToken("-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	112: AddedToken("(-:", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	113: AddedToken("(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	114: AddedToken("(:-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	115: AddedToken("-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	116: AddedToken("8-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	117: AddedToken("'-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	118: AddedToken(":-#", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	119: AddedToken(":-*", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	120: AddedToken(":-/", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	121: AddedToken(":->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	122: AddedToken(":-@", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	123: AddedToken(":-d", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	124: AddedToken(":-V", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	125: AddedToken(":-X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	126: AddedToken(":-\", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	127: AddedToken(":-]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	128: AddedToken(";-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	129: AddedToken(">;->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	130: AddedToken(";^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	131: AddedToken("%-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	132: AddedToken("):-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	133: AddedToken("3:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	134: AddedToken(":-&", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	135: AddedToken("8:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	136: AddedToken(":-)8<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	137: AddedToken(":-O", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	138: AddedToken(":-6", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	139: AddedToken("+:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	140: AddedToken("O:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	141: AddedToken(":-<", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	142: AddedToken(":-?", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	143: AddedToken(":-E", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	144: AddedToken(":-Q", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	145: AddedToken(":-}X", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	146: AddedToken(":-[", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	147: AddedToken(":-a", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	148: AddedToken(":-{", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	149: AddedToken(":-{}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	150: AddedToken(":^)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	151: AddedToken("<:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	152: AddedToken(":=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	153: AddedToken(">:->", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	154: AddedToken(">:-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	155: AddedToken("@:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	156: AddedToken("@:-}", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	157: AddedToken("C=:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	158: AddedToken("X:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	159: AddedToken("[:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	160: AddedToken("[:]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	161: AddedToken("{:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	162: AddedToken("l^o", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	163: AddedToken("}:^#)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	164: AddedToken(":-(=)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	165: AddedToken("O-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	166: AddedToken(":-3", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	167: AddedToken(":=", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	168: AddedToken(":-"", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	169: AddedToken("P-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	170: AddedToken("?-(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	171: AddedToken("d:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	172: AddedToken(":8)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	173: AddedToken(":-7", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	174: AddedToken("):-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	175: AddedToken(":/\)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	176: AddedToken("8(:-)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	177: AddedToken("([(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	178: AddedToken(":-(*)", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	179: AddedToken("&-l", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	180: AddedToken(":-e", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	181: AddedToken(":(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	182: AddedToken(":,(", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),

In [25]:
class SFT_dataset(Dataset):

    def __init__(self, data_path_1_SFT: str, tokenizer: transformers.PreTrainedTokenizer, verbose=False):
        super(SFT_dataset, self).__init__()
        logging.warning("Loading data...")

        pattern_instruction = 'prompt'  # instruction
        pattern_output = 'completion'  # response

        with open(data_path_1_SFT, "r", encoding='utf-8-sig') as json_file:
            list_data_dict = json.load(json_file)

        PROMPT_DICT = {
            "prompt_input": (
                "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
            )
        }

        prompt_input = PROMPT_DICT["prompt_input"]

        sources = []
        for example in list_data_dict:
            tmp = prompt_input.format_map(example)
            sources.append(tmp)

        targets = []
        for example in list_data_dict:
            targets.append(f"{example[pattern_output]}{tokenizer.eos_token}")
        examples = [s + t for s, t in zip(sources, targets)]

        sources_tokenized = self._tokenize_fn(sources, tokenizer)  # source
        examples_tokenized = self._tokenize_fn(examples, tokenizer)  # source + target

        input_ids = examples_tokenized["input_ids"]
        labels = copy.deepcopy(input_ids)
        for label, source_len in zip(labels, sources_tokenized["input_ids_lens"]):
            label[:source_len] = -100

        data_dict = dict(input_ids=input_ids, labels=labels)

        self.input_ids = data_dict["input_ids"]
        self.labels = data_dict["labels"]
        logging.warning("Loading data done!!: %d"%(len(self.labels)))

    def _tokenize_fn(self, strings: Sequence[str], tokenizer: transformers.PreTrainedTokenizer) -> Dict:
        tokenized_list = [
            tokenizer(
                text,
                return_tensors="pt",
                padding="longest",
                max_length=tokenizer.model_max_length,
                truncation=True,
            )
            for text in strings
        ]
        input_ids = labels = [tokenized.input_ids[0] for tokenized in tokenized_list]
        input_ids_lens = labels_lens = [
            tokenized.input_ids.ne(tokenizer.pad_token_id).sum().item() for tokenized in tokenized_list
        ]
        return dict(
            input_ids=input_ids,
            labels=labels,
            input_ids_lens=input_ids_lens,
            labels_lens=labels_lens,
        )

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, i) -> Dict[str, torch.Tensor]:
        return dict(input_ids=self.input_ids[i], labels=self.labels[i])

In [26]:
@dataclass
class DataCollatorForSupervisedDataset(object):

    tokenizer: transformers.PreTrainedTokenizer

    def __call__(self, instances: Sequence[Dict]) -> Dict[str, torch.Tensor]:
        input_ids, labels = tuple([instance[key] for instance in instances] for key in ("input_ids", "labels"))
        input_ids = torch.nn.utils.rnn.pad_sequence(
            input_ids, batch_first=True, padding_value=self.tokenizer.pad_token_id
        )
        labels = torch.nn.utils.rnn.pad_sequence(labels, batch_first=True, padding_value= -100)
        return dict(
            input_ids=input_ids,
            labels=labels,
            attention_mask=input_ids.ne(self.tokenizer.pad_token_id),
        )

In [27]:
train_dataset = SFT_dataset(data_path_1_SFT=cfg.data_path_1_SFT, tokenizer=tokenizer)
data_collator = DataCollatorForSupervisedDataset(tokenizer=tokenizer)

print('input : %s'%train_dataset.input_ids[0])
print('output: %s'%train_dataset.labels[0])

WARNING:root:Loading data...
WARNING:root:Loading data done!!: 12000

input : tensor([  739,   378,   378,   378, 14659, 13394, 37091, 10651,   383, 25841,
         8006, 14914,   375,  7673, 20479,  8091, 22311,  9036, 30902, 13675,
          375,   378,   378,   378, 41951,   454,  9549, 20549,   383,  8142,
         7192, 14914,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])
output: tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,
         -100,  -100,   382, 37767, 13753,  8263,  7166,   739,  8352,  7659,
         9594, 25585, 13600,  8022,  9378, 11532,  9887, 11218,  9111, 16691,
        10351, 10561,  9128, 20479,  8091,  9065,  9446,  9036, 28420, 26521,
        10163, 26367,  6958,  9030,  9882, 12317, 25882,  9209, 37194, 10351,
         9036, 12168, 10529, 15989,  9719, 15434, 10552, 11188, 13362,  9036,
        15805, 11300, 11846,  9146, 16691,  9181,  7397, 15806, 13480, 11342,
        17596,  9161, 19996,  9025, 25006, 18595,  9966, 12592, 10751, 11814,
         8711,  9046, 12450,  9117,  7377, 12521,     1])

In [28]:
print(tokenizer.decode(train_dataset.input_ids[0], skip_special_tokens=False))
print(tokenizer.decode(train_dataset.input_ids[0], skip_special_tokens=True))

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.</s>
### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 인공지능 챗봇이며, 직접적으로 식품에 관한 정보를 가지고 있지 않습니다. 하지만 일반적으로 불고기용 고기는 한우, 쇠고기, 돼지고기 등 다양한 종류의 고기를 사용합니다. 하지만 한우는 대표적인 고급 육류로 알려져 있기 때문에, 한우를 사용하는 경우도 많습니다. 알러지나 개별 건강 상태에 따라 다를 수 있으니 충분한 정보 수집 후에 선택해 주시기 바랍니다.

In [29]:
training_args = transformers.TrainingArguments(
    output_dir=cfg.sft_training_dir,
    num_train_epochs=cfg.sft_num_train_epochs,
    per_device_train_batch_size=cfg.sft_per_device_train_batch_size,
    per_device_eval_batch_size=cfg.sft_per_device_eval_batch_size,
    warmup_steps=cfg.sft_warmup_steps,
    prediction_loss_only=True,
    fp16=cfg.sft_fp16,
)
trainer = transformers.Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
)

In [30]:
trainer.train()
model.save_pretrained(cfg.output_dir_SFT)

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

### 정제 데이터셋으로 SFT 재학습

In [31]:
# ── 정제된 SFT 데이터로 재학습 (데이터셋 정제 전략) ────────────────────
import os

clean_path = cfg.data_path_1_SFT_clean
if not os.path.exists(clean_path):
    print(f"[WARN] 정제 데이터 파일 없음: {clean_path}")
    print("       EDA 정제 셀을 먼저 실행하세요.")
else:
    print(f"정제 데이터 로드: {clean_path}")
    model_clean = AutoModelForCausalLM.from_pretrained(cfg.model_name)
    tok_clean = PreTrainedTokenizerFast.from_pretrained(
        cfg.model_name,
        bos_token=cfg.bos_token, eos_token=cfg.eos_token,
        unk_token=cfg.unk_token, pad_token=cfg.pad_token,
        padding_side=cfg.padding_side,
        model_max_length=cfg.model_max_length,
    )

    train_dataset_clean = SFT_dataset(data_path_1_SFT=clean_path, tokenizer=tok_clean)
    collator_clean = DataCollatorForSupervisedDataset(tokenizer=tok_clean)

    training_args_clean = transformers.TrainingArguments(
        output_dir=cfg.sft_training_dir + "_clean",
        num_train_epochs=cfg.sft_num_train_epochs,
        per_device_train_batch_size=cfg.sft_per_device_train_batch_size,
        per_device_eval_batch_size=cfg.sft_per_device_eval_batch_size,
        warmup_steps=cfg.sft_warmup_steps,
        prediction_loss_only=True,
        fp16=cfg.sft_fp16,
    )
    trainer_clean = transformers.Trainer(
        model=model_clean,
        args=training_args_clean,
        data_collator=collator_clean,
        train_dataset=train_dataset_clean,
    )
    trainer_clean.train()
    model_clean.save_pretrained(cfg.output_dir_SFT + "_clean")
    print(f"정제 데이터 SFT 모델 저장 완료: {cfg.output_dir_SFT}_clean")

정제 데이터 로드: KoChatGPT/data_kochatgpt/kochatgpt_1_SFT_clean.jsonl

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
WARNING:root:Loading data...
WARNING:root:Loading data done!!: 11553

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

정제 데이터 SFT 모델 저장 완료: models/output_1_SFT_clean

In [32]:
generator = transformers.pipeline('text-generation', model=cfg.output_dir_SFT, tokenizer=tokenizer)

generation_args = dict(
    num_beams=cfg.gen_num_beams,
    repetition_penalty=cfg.gen_repetition_penalty,
    no_repeat_ngram_size=cfg.gen_no_repeat_ngram_size,
    eos_token_id=cfg.gen_eos_token_id,
    max_new_tokens=cfg.gen_max_new_tokens,
    do_sample=True,
    top_k=cfg.gen_top_k,
    early_stopping=True,
)

PROMPT_DICT = {
    "prompt_input": (
        "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"
    )
}

list_prompt = ['불고기용 고기 한우에요?',
               '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
               '시카고 오헤어 국제공항은 어디에 있어?',
               '오늘 미세먼지 어때?']

list_prompt = [PROMPT_DICT['prompt_input'].format_map({'prompt': tmp}) for tmp in list_prompt]

list_result = generator(list_prompt, **generation_args)
for prompt, result in zip(list_prompt, list_result):
    print()
    print((result[0]['generated_text']))

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Passing `generation_config` together with generation-related arguments=({'top_k', 'max_new_tokens', 'num_beams', 'early_stopping', 'do_sample', 'eos_token_id', 'no_repeat_ngram_size', 'repetition_penalty'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

### Instruction(명령어):
불고기용 고기 한우에요?

### Response(응답):'저는 AI 어시스턴트이기 때문에 고기를 먹을 수는 없습니다. 하지만 일반적으로 불고기용 고기는 건강에 좋은 음식 중 하나입니다. 따라서 건강한 식습관을 유지하는 것이 중요합니다. 또한, 불고기용 고기를 먹는 것은 개인의 건강에도 매우 중요한 요소입니다.ч́

### Instruction(명령어):
리처드 닉슨이 43대 부통령직을 수행한 년도는?

### Response(응답):'리처드 닉슨은 41대 부통령직을 수행하는 년도는 없습니다. 따라서 리처드 닉슨이 47대 부통령직을 수행했는지에 대한 정보는 제공되지 않았습니다.媒體的, information and context of the translation of the phrase of the referring to

### Instruction(명령어):
시카고 오헤어 국제공항은 어디에 있어?

### Response(응답):'저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고는 미국 캘리포니아주 로스앤젤레스에 위치한 도시 중 하나입니다.高橋)은 시카고에서 가장 유명한 도시 중 하나이며, 현재까지도 많은 사람들이 방문하고 있습니다.高橋)는 시카고에서 가장 오래된 도시 중 하나이다.高

### Instruction(명령어):
오늘 미세먼지 어때?

### Response(응답):'저는 인공지능 챗봇이기 때문에 미세먼지에 대한 정보를 알 수 없습니다. 하지만, 미세먼지 농도가 높은 날에는 실외 활동을 자제하는 것이 좋습니다. 또한, 미세먼지가 심한 날에는 대중교통을 이용하거나 대중교통을 이용하는 것도 도움이 될 수 있습니다. 또한 미세먼지 농도를 줄이기 위해 마스크

In [33]:
torch.cuda.empty_cache()

### Base vs SFT 비교 평가

In [34]:
# ── Base KoGPT2 vs SFT: 정성 평가 ────────────────────────────────────────
import torch, transformers
from transformers import AutoModelForCausalLM, PreTrainedTokenizerFast

device = "cuda" if torch.cuda.is_available() else "cpu"

# Base 모델 로드
base_gen = transformers.pipeline(
    'text-generation',
    model=cfg.model_name,
    tokenizer=PreTrainedTokenizerFast.from_pretrained(cfg.model_name),
    device=0 if torch.cuda.is_available() else -1,
)

# SFT 모델 로드
sft_gen = transformers.pipeline(
    'text-generation',
    model=cfg.output_dir_SFT,
    tokenizer=PreTrainedTokenizerFast.from_pretrained(
        cfg.model_name,
        bos_token=cfg.bos_token, eos_token=cfg.eos_token,
        unk_token=cfg.unk_token, pad_token=cfg.pad_token,
    ),
    device=0 if torch.cuda.is_available() else -1,
)

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}

eval_prompts_qualitative = [
    '불고기용 고기 한우에요?',
    '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
    '시카고 오헤어 국제공항은 어디에 있어?',
    '인공지능이 미래 사회에 미치는 영향은?',
]

gen_kwargs = dict(
    max_new_tokens=cfg.gen_max_new_tokens,
    do_sample=True,
    top_k=cfg.gen_top_k,
    num_beams=cfg.gen_num_beams,
    repetition_penalty=cfg.gen_repetition_penalty,
    no_repeat_ngram_size=cfg.gen_no_repeat_ngram_size,
    eos_token_id=cfg.gen_eos_token_id,
    early_stopping=True,
)

print("=" * 80)
print("[정성 평가] Base KoGPT2 vs SFT 모델")
print("=" * 80)
for raw_p in eval_prompts_qualitative:
    p = PROMPT_DICT['prompt_input'].format_map({'prompt': raw_p})
    base_out = base_gen(p, **gen_kwargs)[0]['generated_text']
    sft_out  = sft_gen(p,  **gen_kwargs)[0]['generated_text']
    print(f"\n[PROMPT] {raw_p}")
    print(f"  [Base] {base_out[len(p):][:150]}")
    print(f"  [SFT]  {sft_out[len(p):][:150]}")

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
[정성 평가] Base KoGPT2 vs SFT 모델
================================================================================

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 불고기용 고기 한우에요?
  [Base]  #selfie #delicious #good #instafood #like4like #소통 #좋아요
#팔로우 #맞팔 #선팔 #일상 #데일리 #먹
  [SFT]  '저는 인공지능 어시스턴트이기 때문에 고기를 먹을 수 없습니다. 하지만 일반적으로 불고기용 고기는 보통 쇠고기, 돼지고기, 닭고기 등 다양한 요리에 사용됩니다. 그러나 일부 음식점에서는 불고기용 고기를 판매하기도 합니다.證)增)增)으로 구성되어 있습니다.增)로 구성되어

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 리처드 닉슨이 43대 부통령직을 수행한 년도는?
  [Base]

  [SFT]  '리처드 닉슨은 41대 부통령직을 수행했습니다.子, please translation of the context or information.子: 36대 부통령직을 맡았던 년도는 1952년입니다.子): 38대 부통령직을 맡은 년도는 1951년입니다.子

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 시카고 오헤어 국제공항은 어디에 있어?
  [Base]  #selfie #daily #ootd #outfit #like4like #instagood #followme #fff #l4l #lfl #f4f

  [SFT]  '저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고 오헤어 공항은 미국 캘리포니아주 로스앤젤레스(LA) 지역에 위치해 있습니다.仙橋)은 미국에서 가장 유명한 항공사 중 하나입니다.仙橋라고도 불립니다.仙橋)는 미국의 대표적인

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 인공지능이 미래 사회에 미치는 영향은?
  [Base]  # #20180413 #미롱_식단

  [SFT]  '저는 인공지능 어시스턴트이기 때문에 인간과 같은 생각과 감정을 가지고 있지 않습니다. 하지만 인공지능은 인간보다 더 다양한 분야에서 영향을 미칠 수 있습니다. 예를 들어, 컴퓨터, 스마트폰, TV, 냉장고, 세탁기 등 다양한 분야에서 인공지능 기술이 적용되고 있으며,

In [41]:
# ── Base vs SFT: 정량 평가 (BLEU, ROUGE, Perplexity) ────────────────────
bleu  = evaluate.load("bleu")
rouge = evaluate.load("rouge")

# 평가용 데이터 로드 (정제 파일이 있으면 우선 사용)
import os
sft_eval_path = (cfg.data_path_1_SFT_clean
                 if os.path.exists(cfg.data_path_1_SFT_clean)
                 else cfg.data_path_1_SFT)
with open(sft_eval_path, 'r', encoding='utf-8-sig') as f:
    eval_data = json.load(f)

import random
random.seed(42)
sample = random.sample(eval_data, min(100, len(eval_data)))

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}
prompts   = [PROMPT_DICT['prompt_input'].format_map({'prompt': d['prompt']}) for d in sample]
refs_text = [d['completion'] for d in sample]
refs_bleu = [[r] for r in refs_text]

def batch_generate(pipeline, prompts, batch=8, **kwargs):
    outs = []
    for i in range(0, len(prompts), batch):
        batch_out = pipeline(prompts[i:i+batch], **kwargs)
        for j, res in enumerate(batch_out):
            text = res[0]['generated_text']
            p    = prompts[i+j]
            outs.append(text[len(p):].strip())
    return outs

gen_kw = dict(max_new_tokens=64, do_sample=False, num_beams=4,
              repetition_penalty=2.0, no_repeat_ngram_size=4,
              eos_token_id=cfg.gen_eos_token_id, early_stopping=True)

print("Base 모델 생성 중...")
base_preds = batch_generate(base_gen, prompts, **gen_kw)
print("SFT 모델 생성 중...")
sft_preds  = batch_generate(sft_gen,  prompts, **gen_kw)

# BLEU
b_base = bleu.compute(predictions=base_preds, references=refs_bleu)['bleu']
b_sft  = bleu.compute(predictions=sft_preds,  references=refs_bleu)['bleu']

# ROUGE-L
r_base = rouge.compute(predictions=base_preds, references=refs_text)['rougeL']
r_sft  = rouge.compute(predictions=sft_preds,  references=refs_text)['rougeL']

# Perplexity (샘플 텍스트 기준)
def calc_ppl(model_path, texts, tokenizer_path=None):
    tok_path = tokenizer_path or model_path
    tok = PreTrainedTokenizerFast.from_pretrained(tok_path)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    mdl = AutoModelForCausalLM.from_pretrained(model_path).to(device)
    mdl.eval()
    ppls = []
    for t in texts[:20]:
        enc = tok(t, return_tensors='pt', truncation=True, max_length=256).to(device)
        with torch.no_grad():
            loss = mdl(**enc, labels=enc['input_ids']).loss
        ppls.append(torch.exp(loss).item())
    del mdl
    torch.cuda.empty_cache()
    return sum(ppls)/len(ppls)

print("Perplexity 계산 중 (Base)...")
ppl_base = calc_ppl(cfg.model_name,   refs_text, cfg.model_name)
print("Perplexity 계산 중 (SFT)...")
ppl_sft  = calc_ppl(cfg.output_dir_SFT, refs_text, cfg.model_name)

import pandas as pd
df_eval = pd.DataFrame({
    'Model':       ['Base KoGPT2', 'SFT'],
    'BLEU':        [round(b_base, 4), round(b_sft, 4)],
    'ROUGE-L':     [round(r_base, 4), round(r_sft, 4)],
    'Perplexity ↓':[round(ppl_base,2), round(ppl_sft,2)],
})
print("\n[정량 평가 결과] Base vs SFT")
print(df_eval.to_string(index=False))

The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'num_beams', 'early_stopping', 'do_sample', 'eos_token_id', 'no_repeat_ngram_size', 'repetition_penalty'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Base 모델 생성 중...

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SFT 모델 생성 중...

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Perplexity 계산 중 (Base)...

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Perplexity 계산 중 (SFT)...

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

[정량 평가 결과] Base vs SFT
      Model   BLEU  ROUGE-L  Perplexity ↓
Base KoGPT2 0.0000   0.0005        350.48
        SFT 0.0329   0.0613        459.91

## 4. Reward Model (RM)

In [42]:
class GPTRM_custom(RewardModel):

    def __init__(self,
                 pretrained: Optional[str] = None,
                 config: Optional[GPT2Config] = None,
                 checkpoint: bool = False,
                 lora_rank: int = 0,
                 lora_train_bias: str = 'none',
                 tokenizer=None) -> None:
        if pretrained is not None:
            model = GPT2Model.from_pretrained(pretrained)
            model.resize_token_embeddings(len(tokenizer))
        elif config is not None:
            model = GPT2Model(config)
        else:
            model = GPT2Model(GPT2Config())
        if checkpoint:
            model.gradient_checkpointing_enable()

        value_head = nn.Linear(model.config.n_embd, 1)
        super().__init__(model, value_head, lora_rank, lora_train_bias)

        if pretrained is not None:
            self.model = model
            self.pretrained = pretrained

    def save_pretrained(self, dir):
        if self.pretrained is not None:
            self.model.save_pretrained(dir)

In [43]:
model = AutoModelForCausalLM.from_pretrained(cfg.model_name)
tokenizer = PreTrainedTokenizerFast.from_pretrained(
    cfg.model_name,
    bos_token=cfg.bos_token, eos_token=cfg.eos_token,
    unk_token=cfg.unk_token, pad_token=cfg.pad_token,
    padding_side=cfg.padding_side,
    model_max_length=cfg.model_max_length,
)
with NaiveStrategy().model_init_context():
    model = GPTRM_custom(pretrained=cfg.model_name, lora_rank=0, tokenizer=tokenizer).cuda()

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2Model LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |
lm_head.weight                          | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [44]:
with open(cfg.data_path_2_RM, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)

total_data_ranking2chosen = []
for tmp in list_data_dict:
    one_data_ranking2chosen = []

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][1]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_1']
    else:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][0] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_0']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_0']
    one_data_ranking2chosen.append(data)

    data = {}
    data['prompt'] = tmp['prompt']
    if tmp['ranking'][1] < tmp['ranking'][2]:
        data['chosen'] = tmp['completion_1']
        data['rejected'] = tmp['completion_2']
    else:
        data['chosen'] = tmp['completion_2']
        data['rejected'] = tmp['completion_1']
    one_data_ranking2chosen.append(data)

    total_data_ranking2chosen.extend(one_data_ranking2chosen)

print('before data num: %d'%(len(list_data_dict)))
print('after  data num: %d'%(len(total_data_ranking2chosen)))
print('data example: \n%s'%total_data_ranking2chosen[45])

before data num: 10220
after  data num: 30660
data example:
{'prompt': '애플은 리사를 어떻게 처리했어', 'chosen': '애플이 누구인지 명확히 알 수 없어서, 리사가 누구인지와 어떤 상황에서 처리되었는지에 대한 추가적인 정보가 필요합니다. 따라서, 보다 정확한 답변을 제공할 수 없습니다.', 'rejected': '애플은 리사를 위해 고객 서비스 부서에서 고객 다양한 컴퓨터 관련 문제에 대해 응답하는 데 필요한 모든 지원을 제공했습니다. 사용자가 하드웨어 문제를 경험할 때, 전문가들은 필요한 수리(수리, 추가 부품 제공, 소프트웨어 업그레이드 등)을 제공해 드릴 수 있습니다. 또한, 사용자가 사용 방법 문제나 기타 문제를 경험할 때, 대화 상대로 사용자를 지원할 수 있는 전문 고객 서비스 직원들이 사용자에게 상담하고 도움을 주는 데 도움이 될 수 있는 정보를 제공합니다. 또한, 인터넷에서 제공되는 정보를 통해 문제를 해결하거나 고객 서비스 웹 사이트를 통해 자신의 문제를 진단할 수 있도록 하는 등 다양한 방법으로 리사를 처리해 왔습니다.'}

In [45]:
random.seed(cfg.rm_random_seed)
random.shuffle(total_data_ranking2chosen)
print(total_data_ranking2chosen[45])

{'prompt': '유아인이 류승완 감독을 만나 영화 베테랑의 시나리오를 받았던 곳은?', 'chosen': '유아인이 류승완 감독을 만나 영화 베테랑의 시나리오를 받았던 곳은 류승완의 사무실입니다.', 'rejected': '대구 영화사옥'}

In [46]:
train_data = total_data_ranking2chosen[:cfg.rm_train_size]
eval_data  = total_data_ranking2chosen[cfg.rm_train_size:cfg.rm_eval_size]

print(len(train_data))
print(len(eval_data))

train_dataset = RewardDataset(train_data, tokenizer, cfg.model_max_length)
eval_dataset  = RewardDataset(eval_data,  tokenizer, cfg.model_max_length)

1000
200

  0%|          | 0/1000 [00:00<?, ?it/s]

  0%|          | 0/200 [00:00<?, ?it/s]

In [47]:
idx = 1
print('#'*70)
print('## prompt ##')
print(train_data[idx]['prompt'])
print('#'*70)
print('## chosen ##')
print(train_data[idx]['chosen'])
print('#'*70)
print('## rejected ##')
print(train_data[idx]['rejected'])

######################################################################
## prompt ##
흑고래의 무게는 어느 정도야
######################################################################
## chosen ##
흑고래의 평균 몸무게는 약 25~40톤 정도이지만, 최대 몸무게는 50톤 이상에 이를 수 있습니다.
######################################################################
## rejected ##
흑고래의 무게는 매우 다양하게 달라집니다. 약 200kg에서 10톤까지 달라질 수 있습니다.

In [48]:
trainer = RewardModelTrainer(
    model=model,
    strategy=NaiveStrategy(),
    optim=torch.optim.Adam(model.parameters(), lr=cfg.rm_lr),
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    batch_size=cfg.rm_batch_size,
    max_epochs=cfg.rm_max_epochs,
)

In [49]:
trainer.fit(use_lora=0)
model.save_pretrained(cfg.output_dir_RM)

Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 0/250 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 1/250 [00:01<05:20,  1.29s/it]
Train step of epoch 0:   0%|          | 1/250 [00:01<05:20,  1.29s/it, loss=0.687]
Train step of epoch 0:   1%|          | 2/250 [00:02<04:35,  1.11s/it, loss=0.687]
Train step of epoch 0:   1%|          | 2/250 [00:02<04:35,  1.11s/it, loss=0.49]
Train step of epoch 0:   1%|          | 3/250 [00:03<04:18,  1.05s/it, loss=0.49]
Train step of epoch 0:   1%|          | 3/250 [00:03<04:18,  1.05s/it, loss=0.414]
Train step of epoch 0:   2%|▏         | 4/250 [00:04<04:10,  1.02s/it, loss=0.414]
Train step of epoch 0:   2%|▏         | 4/250 [00:04<04:10,  1.02s/it, loss=0.62]
Train step of epoch 0:   2%|▏         | 5/250 [00:05<04:05,  1.00s/it, loss=0.62]
Train step of epoch 0:   2%|▏         | 5/250 [00:05<04:05,  1.00s/it, loss=0.339]
Train step of epoch 0:   2%|▏         | 6/250 [00:06<04:02,  1.00it/s, loss=0.339]
Train step of epoch 0:   2%|▏         | 6/250 [00:06<04:02,  1.00it/s, loss=0.672]
Train step of epoch 0:   3%|▎         | 7/250 [00:07<04:01,  1.01it/s, loss=0.672]
Train step of epoch 0:   3%|▎         | 7/250 [00:07<04:01,  1.01it/s, loss=0.487]
Train step of epoch 0:   3%|▎         | 8/250 [00:08<03:59,  1.01it/s, loss=0.487]
Train step of epoch 0:   3%|▎         | 8/250 [00:08<03:59,  1.01it/s, loss=2.66]
Train step of epoch 0:   4%|▎         | 9/250 [00:09<03:58,  1.01it/s, loss=2.66]
Train step of epoch 0:   4%|▎         | 9/250 [00:09<03:58,  1.01it/s, loss=0.298]
Train step of epoch 0:   4%|▍         | 10/250 [00:10<03:57,  1.01it/s, loss=0.298]
Train step of epoch 0:   4%|▍         | 10/250 [00:10<03:57,  1.01it/s, loss=0.857]
Train step of epoch 0:   4%|▍         | 11/250 [00:11<03:57,  1.01it/s, loss=0.857]
Train step of epoch 0:   4%|▍         | 11/250 [00:11<03:57,  1.01it/s, loss=0.363]
Train step of epoch 0:   5%|▍         | 12/250 [00:12<03:56,  1.01it/s, loss=0.363]
Train step of epoch 0:   5%|▍         | 12/250 [00:12<03:56,  1.01it/s, loss=0.44]
Train step of epoch 0:   5%|▌         | 13/250 [00:13<03:58,  1.01s/it, loss=0.44]
Train step of epoch 0:   5%|▌         | 13/250 [00:13<03:58,  1.01s/it, loss=0.217]
Train step of epoch 0:   6%|▌         | 14/250 [00:14<04:19,  1.10s/it, loss=0.217]
Train step of epoch 0:   6%|▌         | 14/250 [00:14<04:19,  1.10s/it, loss=1.28]
Train step of epoch 0:   6%|▌         | 15/250 [00:15<04:32,  1.16s/it, loss=1.28]
Train step of epoch 0:   6%|▌         | 15/250 [00:15<04:32,  1.16s/it, loss=0.49]
Train step of epoch 0:   6%|▋         | 16/250 [00:17<04:38,  1.19s/it, loss=0.49]
Train step of epoch 0:   6%|▋         | 16/250 [00:17<04:38,  1.19s/it, loss=1.51]
Train step of epoch 0:   7%|▋         | 17/250 [00:18<04:26,  1.15s/it, loss=1.51]
Train step of epoch 0:   7%|▋         | 17/250 [00:18<04:26,  1.15s/it, loss=0.705]
Train step of epoch 0:   7%|▋         | 18/250 [00:19<04:14,  1.10s/it, loss=0.705]
Train step of epoch 0:   7%|▋         | 18/250 [00:19<04:14,  1.10s/it, loss=0.538]
Train step of epoch 0:   8%|▊         | 19/250 [00:20<04:06,  1.07s/it, loss=0.538]
Train step of epoch 0:   8%|▊         | 19/250 [00:20<04:06,  1.07s/it, loss=0.796]
Train step of epoch 0:   8%|▊         | 20/250 [00:21<03:59,  1.04s/it, loss=0.796]
Train step of epoch 0:   8%|▊         | 20/250 [00:21<03:59,  1.04s/it, loss=0.583]
Train step of epoch 0:   8%|▊         | 21/250 [00:22<03:55,  1.03s/it, loss=0.583]
Train step of epoch 0:   8%|▊         | 21/250 [00:22<03:55,  1.03s/it, loss=0.721]
Train step of epoch 0:   9%|▉         | 22/250 [00:23<03:50,  1.01s/it, loss=0.721]
Train step of epoch 0:   9%|▉         | 22/250 [00:23<03:50,  1.01s/it, loss=0.669]
Train step of epoch 0:   9%|▉         | 23/250 [00:23<03:47,  1.00s/it, loss=0.669]
Train step of epoch 0:   9%|▉         | 23/250 [00:23<03:47,  1.00s/it, loss=0.898]
Train step of epoch 0:  10%|▉         | 24/250 [00:24<03:44,  1.01it/s, loss=0.898]
Train step of epoch 0:  10%|▉         | 24/250 [00:24<03:44,  1.01it/s, loss=0.596]
Train step of epoch 0:  10%|█         | 25/250 [00:25<03:41,  1.02it/s, loss=0.596]
Train step of epoch 0:  10%|█         | 25/250 [00:25<03:41,  1.02it/s, loss=0.553]
Train step of epoch 0:  10%|█         | 26/250 [00:26<03:39,  1.02it/s, loss=0.553]
Train step of epoch 0:  10%|█         | 26/250 [00:26<03:39,  1.02it/s, loss=0.674]
Train step of epoch 0:  11%|█         | 27/250 [00:27<03:37,  1.03it/s, loss=0.674]
Train step of epoch 0:  11%|█         | 27/250 [00:27<03:37,  1.03it/s, loss=0.612]
Train step of epoch 0:  11%|█         | 28/250 [00:28<03:35,  1.03it/s, loss=0.612]
Train step of epoch 0:  11%|█         | 28/250 [00:28<03:35,  1.03it/s, loss=0.581]
Train step of epoch 0:  12%|█▏        | 29/250 [00:29<03:34,  1.03it/s, loss=0.581]
Train step of epoch 0:  12%|█▏        | 29/250 [00:29<03:34,  1.03it/s, loss=0.566]
Train step of epoch 0:  12%|█▏        | 30/250 [00:30<03:32,  1.04it/s, loss=0.566]
Train step of epoch 0:  12%|█▏        | 30/250 [00:30<03:32,  1.04it/s, loss=0.484]
Train step of epoch 0:  12%|█▏        | 31/250 [00:31<03:31,  1.04it/s, loss=0.484]
Train step of epoch 0:  12%|█▏        | 31/250 [00:31<03:31,  1.04it/s, loss=0.337]
Train step of epoch 0:  13%|█▎        | 32/250 [00:32<03:29,  1.04it/s, loss=0.337]
Train step of epoch 0:  13%|█▎        | 32/250 [00:32<03:29,  1.04it/s, loss=1.04]
Train step of epoch 0:  13%|█▎        | 33/250 [00:33<03:28,  1.04it/s, loss=1.04]
Train step of epoch 0:  13%|█▎        | 33/250 [00:33<03:28,  1.04it/s, loss=0.415]
Train step of epoch 0:  14%|█▎        | 34/250 [00:34<03:27,  1.04it/s, loss=0.415]
Train step of epoch 0:  14%|█▎        | 34/250 [00:34<03:27,  1.04it/s, loss=0.381]
Train step of epoch 0:  14%|█▍        | 35/250 [00:35<03:25,  1.04it/s, loss=0.381]
Train step of epoch 0:  14%|█▍        | 35/250 [00:35<03:25,  1.04it/s, loss=0.776]
Train step of epoch 0:  14%|█▍        | 36/250 [00:36<03:24,  1.05it/s, loss=0.776]
Train step of epoch 0:  14%|█▍        | 36/250 [00:36<03:24,  1.05it/s, loss=1.81]
Train step of epoch 0:  15%|█▍        | 37/250 [00:37<03:22,  1.05it/s, loss=1.81]
Train step of epoch 0:  15%|█▍        | 37/250 [00:37<03:22,  1.05it/s, loss=1.09]
Train step of epoch 0:  15%|█▌        | 38/250 [00:38<03:21,  1.05it/s, loss=1.09]
Train step of epoch 0:  15%|█▌        | 38/250 [00:38<03:21,  1.05it/s, loss=0.606]
Train step of epoch 0:  16%|█▌        | 39/250 [00:39<03:20,  1.05it/s, loss=0.606]
Train step of epoch 0:  16%|█▌        | 39/250 [00:39<03:20,  1.05it/s, loss=0.703]
Train step of epoch 0:  16%|█▌        | 40/250 [00:40<03:18,  1.06it/s, loss=0.703]
Train step of epoch 0:  16%|█▌        | 40/250 [00:40<03:18,  1.06it/s, loss=0.439]
Train step of epoch 0:  16%|█▋        | 41/250 [00:41<03:17,  1.06it/s, loss=0.439]
Train step of epoch 0:  16%|█▋        | 41/250 [00:41<03:17,  1.06it/s, loss=0.35]
Train step of epoch 0:  17%|█▋        | 42/250 [00:42<03:16,  1.06it/s, loss=0.35]
Train step of epoch 0:  17%|█▋        | 42/250 [00:42<03:16,  1.06it/s, loss=0.66]
Train step of epoch 0:  17%|█▋        | 43/250 [00:43<03:15,  1.06it/s, loss=0.66]
Train step of epoch 0:  17%|█▋        | 43/250 [00:43<03:15,  1.06it/s, loss=0.679]
Train step of epoch 0:  18%|█▊        | 44/250 [00:44<03:14,  1.06it/s, loss=0.679]
Train step of epoch 0:  18%|█▊        | 44/250 [00:44<03:14,  1.06it/s, loss=0.948]
Train step of epoch 0:  18%|█▊        | 45/250 [00:44<03:13,  1.06it/s, loss=0.948]
Train step of epoch 0:  18%|█▊        | 45/250 [00:44<03:13,  1.06it/s, loss=0.685]
Train step of epoch 0:  18%|█▊        | 46/250 [00:45<03:12,  1.06it/s, loss=0.685]
Train step of epoch 0:  18%|█▊        | 46/250 [00:45<03:12,  1.06it/s, loss=0.58]
Train step of epoch 0:  19%|█▉        | 47/250 [00:46<03:10,  1.06it/s, loss=0.58]
Train step of epoch 0:  19%|█▉        | 47/250 [00:46<03:10,  1.06it/s, loss=0.634]
Train step of epoch 0:  19%|█▉        | 48/250 [00:47<03:09,  1.07it/s, loss=0.634]
Train step of epoch 0:  19%|█▉        | 48/250 [00:47<03:09,  1.07it/s, loss=0.721]
Train step of epoch 0:  20%|█▉        | 49/250 [00:48<03:08,  1.07it/s, loss=0.721]
Train step of epoch 0:  20%|█▉        | 49/250 [00:48<03:08,  1.07it/s, loss=0.621]
Train step of epoch 0:  20%|██        | 50/250 [00:49<03:07,  1.07it/s, loss=0.621]
Train step of epoch 0:  20%|██        | 50/250 [00:49<03:07,  1.07it/s, loss=0.763]
Train step of epoch 0:  20%|██        | 51/250 [00:50<03:05,  1.07it/s, loss=0.763]
Train step of epoch 0:  20%|██        | 51/250 [00:50<03:05,  1.07it/s, loss=0.478]
Train step of epoch 0:  21%|██        | 52/250 [00:51<03:05,  1.07it/s, loss=0.478]
Train step of epoch 0:  21%|██        | 52/250 [00:51<03:05,  1.07it/s, loss=0.635]
Train step of epoch 0:  21%|██        | 53/250 [00:52<03:04,  1.07it/s, loss=0.635]
Train step of epoch 0:  21%|██        | 53/250 [00:52<03:04,  1.07it/s, loss=0.467]
Train step of epoch 0:  22%|██▏       | 54/250 [00:53<03:03,  1.07it/s, loss=0.467]
Train step of epoch 0:  22%|██▏       | 54/250 [00:53<03:03,  1.07it/s, loss=0.431]
Train step of epoch 0:  22%|██▏       | 55/250 [00:54<03:02,  1.07it/s, loss=0.431]
Train step of epoch 0:  22%|██▏       | 55/250 [00:54<03:02,  1.07it/s, loss=0.62]
Train step of epoch 0:  22%|██▏       | 56/250 [00:55<03:01,  1.07it/s, loss=0.62]
Train step of epoch 0:  22%|██▏       | 56/250 [00:55<03:01,  1.07it/s, loss=0.639]
Train step of epoch 0:  23%|██▎       | 57/250 [00:56<03:00,  1.07it/s, loss=0.639]
Train step of epoch 0:  23%|██▎       | 57/250 [00:56<03:00,  1.07it/s, loss=0.482]
Train step of epoch 0:  23%|██▎       | 58/250 [00:57<02:59,  1.07it/s, loss=0.482]
Train step of epoch 0:  23%|██▎       | 58/250 [00:57<02:59,  1.07it/s, loss=0.519]
Train step of epoch 0:  24%|██▎       | 59/250 [00:58<02:58,  1.07it/s, loss=0.519]
Train step of epoch 0:  24%|██▎       | 59/250 [00:58<02:58,  1.07it/s, loss=0.505]
Train step of epoch 0:  24%|██▍       | 60/250 [00:58<02:57,  1.07it/s, loss=0.505]
Train step of epoch 0:  24%|██▍       | 60/250 [00:58<02:57,  1.07it/s, loss=0.349]
Train step of epoch 0:  24%|██▍       | 61/250 [00:59<02:56,  1.07it/s, loss=0.349]
Train step of epoch 0:  24%|██▍       | 61/250 [00:59<02:56,  1.07it/s, loss=1]
Train step of epoch 0:  25%|██▍       | 62/250 [01:00<02:55,  1.07it/s, loss=1]
Train step of epoch 0:  25%|██▍       | 62/250 [01:00<02:55,  1.07it/s, loss=0.23]
Train step of epoch 0:  25%|██▌       | 63/250 [01:01<02:55,  1.07it/s, loss=0.23]
Train step of epoch 0:  25%|██▌       | 63/250 [01:01<02:55,  1.07it/s, loss=1.02]
Train step of epoch 0:  26%|██▌       | 64/250 [01:02<02:54,  1.07it/s, loss=1.02]
Train step of epoch 0:  26%|██▌       | 64/250 [01:02<02:54,  1.07it/s, loss=0.378]
Train step of epoch 0:  26%|██▌       | 65/250 [01:03<02:52,  1.07it/s, loss=0.378]
Train step of epoch 0:  26%|██▌       | 65/250 [01:03<02:52,  1.07it/s, loss=0.553]
Train step of epoch 0:  26%|██▋       | 66/250 [01:04<02:51,  1.07it/s, loss=0.553]
Train step of epoch 0:  26%|██▋       | 66/250 [01:04<02:51,  1.07it/s, loss=0.146]
Train step of epoch 0:  27%|██▋       | 67/250 [01:05<02:51,  1.07it/s, loss=0.146]
Train step of epoch 0:  27%|██▋       | 67/250 [01:05<02:51,  1.07it/s, loss=0.922]
Train step of epoch 0:  27%|██▋       | 68/250 [01:06<02:50,  1.07it/s, loss=0.922]
Train step of epoch 0:  27%|██▋       | 68/250 [01:06<02:50,  1.07it/s, loss=0.319]
Train step of epoch 0:  28%|██▊       | 69/250 [01:07<02:49,  1.07it/s, loss=0.319]
Train step of epoch 0:  28%|██▊       | 69/250 [01:07<02:49,  1.07it/s, loss=0.619]
Train step of epoch 0:  28%|██▊       | 70/250 [01:08<02:48,  1.07it/s, loss=0.619]
Train step of epoch 0:  28%|██▊       | 70/250 [01:08<02:48,  1.07it/s, loss=0.836]
Train step of epoch 0:  28%|██▊       | 71/250 [01:09<02:48,  1.06it/s, loss=0.836]
Train step of epoch 0:  28%|██▊       | 71/250 [01:09<02:48,  1.06it/s, loss=0.564]
Train step of epoch 0:  29%|██▉       | 72/250 [01:10<02:47,  1.06it/s, loss=0.564]
Train step of epoch 0:  29%|██▉       | 72/250 [01:10<02:47,  1.06it/s, loss=0.732]
Train step of epoch 0:  29%|██▉       | 73/250 [01:11<02:46,  1.07it/s, loss=0.732]
Train step of epoch 0:  29%|██▉       | 73/250 [01:11<02:46,  1.07it/s, loss=0.857]
Train step of epoch 0:  30%|██▉       | 74/250 [01:12<02:45,  1.06it/s, loss=0.857]
Train step of epoch 0:  30%|██▉       | 74/250 [01:12<02:45,  1.06it/s, loss=0.464]
Train step of epoch 0:  30%|███       | 75/250 [01:13<02:44,  1.06it/s, loss=0.464]
Train step of epoch 0:  30%|███       | 75/250 [01:13<02:44,  1.06it/s, loss=0.694]
Train step of epoch 0:  30%|███       | 76/250 [01:13<02:43,  1.06it/s, loss=0.694]
Train step of epoch 0:  30%|███       | 76/250 [01:13<02:43,  1.06it/s, loss=0.766]
Train step of epoch 0:  31%|███       | 77/250 [01:14<02:42,  1.06it/s, loss=0.766]
Train step of epoch 0:  31%|███       | 77/250 [01:14<02:42,  1.06it/s, loss=0.411]
Train step of epoch 0:  31%|███       | 78/250 [01:15<02:41,  1.06it/s, loss=0.411]
Train step of epoch 0:  31%|███       | 78/250 [01:15<02:41,  1.06it/s, loss=0.625]
Train step of epoch 0:  32%|███▏      | 79/250 [01:16<02:40,  1.06it/s, loss=0.625]
Train step of epoch 0:  32%|███▏      | 79/250 [01:16<02:40,  1.06it/s, loss=0.57]
Train step of epoch 0:  32%|███▏      | 80/250 [01:17<02:39,  1.06it/s, loss=0.57]
Train step of epoch 0:  32%|███▏      | 80/250 [01:17<02:39,  1.06it/s, loss=0.707]
Train step of epoch 0:  32%|███▏      | 81/250 [01:18<02:38,  1.06it/s, loss=0.707]
Train step of epoch 0:  32%|███▏      | 81/250 [01:18<02:38,  1.06it/s, loss=0.393]
Train step of epoch 0:  33%|███▎      | 82/250 [01:19<02:38,  1.06it/s, loss=0.393]
Train step of epoch 0:  33%|███▎      | 82/250 [01:19<02:38,  1.06it/s, loss=0.825]
Train step of epoch 0:  33%|███▎      | 83/250 [01:20<02:37,  1.06it/s, loss=0.825]
Train step of epoch 0:  33%|███▎      | 83/250 [01:20<02:37,  1.06it/s, loss=0.569]
Train step of epoch 0:  34%|███▎      | 84/250 [01:21<02:36,  1.06it/s, loss=0.569]
Train step of epoch 0:  34%|███▎      | 84/250 [01:21<02:36,  1.06it/s, loss=0.651]
Train step of epoch 0:  34%|███▍      | 85/250 [01:22<02:36,  1.06it/s, loss=0.651]
Train step of epoch 0:  34%|███▍      | 85/250 [01:22<02:36,  1.06it/s, loss=0.608]
Train step of epoch 0:  34%|███▍      | 86/250 [01:23<02:34,  1.06it/s, loss=0.608]
Train step of epoch 0:  34%|███▍      | 86/250 [01:23<02:34,  1.06it/s, loss=0.598]
Train step of epoch 0:  35%|███▍      | 87/250 [01:24<02:33,  1.06it/s, loss=0.598]
Train step of epoch 0:  35%|███▍      | 87/250 [01:24<02:33,  1.06it/s, loss=0.48]
Train step of epoch 0:  35%|███▌      | 88/250 [01:25<02:33,  1.06it/s, loss=0.48]
Train step of epoch 0:  35%|███▌      | 88/250 [01:25<02:33,  1.06it/s, loss=1.01]
Train step of epoch 0:  36%|███▌      | 89/250 [01:26<02:32,  1.06it/s, loss=1.01]
Train step of epoch 0:  36%|███▌      | 89/250 [01:26<02:32,  1.06it/s, loss=0.866]
Train step of epoch 0:  36%|███▌      | 90/250 [01:27<02:31,  1.06it/s, loss=0.866]
Train step of epoch 0:  36%|███▌      | 90/250 [01:27<02:31,  1.06it/s, loss=0.689]
Train step of epoch 0:  36%|███▋      | 91/250 [01:28<02:30,  1.06it/s, loss=0.689]
Train step of epoch 0:  36%|███▋      | 91/250 [01:28<02:30,  1.06it/s, loss=0.62]
Train step of epoch 0:  37%|███▋      | 92/250 [01:29<02:29,  1.06it/s, loss=0.62]
Train step of epoch 0:  37%|███▋      | 92/250 [01:29<02:29,  1.06it/s, loss=0.61]
Train step of epoch 0:  37%|███▋      | 93/250 [01:30<02:28,  1.06it/s, loss=0.61]
Train step of epoch 0:  37%|███▋      | 93/250 [01:30<02:28,  1.06it/s, loss=0.875]
Train step of epoch 0:  38%|███▊      | 94/250 [01:30<02:27,  1.06it/s, loss=0.875]
Train step of epoch 0:  38%|███▊      | 94/250 [01:31<02:27,  1.06it/s, loss=0.777]
Train step of epoch 0:  38%|███▊      | 95/250 [01:31<02:27,  1.05it/s, loss=0.777]
Train step of epoch 0:  38%|███▊      | 95/250 [01:31<02:27,  1.05it/s, loss=0.529]
Train step of epoch 0:  38%|███▊      | 96/250 [01:32<02:26,  1.05it/s, loss=0.529]
Train step of epoch 0:  38%|███▊      | 96/250 [01:32<02:26,  1.05it/s, loss=0.708]
Train step of epoch 0:  39%|███▉      | 97/250 [01:33<02:25,  1.05it/s, loss=0.708]
Train step of epoch 0:  39%|███▉      | 97/250 [01:33<02:25,  1.05it/s, loss=0.846]
Train step of epoch 0:  39%|███▉      | 98/250 [01:34<02:24,  1.05it/s, loss=0.846]
Train step of epoch 0:  39%|███▉      | 98/250 [01:34<02:24,  1.05it/s, loss=0.757]
Train step of epoch 0:  40%|███▉      | 99/250 [01:35<02:23,  1.05it/s, loss=0.757]
Train step of epoch 0:  40%|███▉      | 99/250 [01:35<02:23,  1.05it/s, loss=0.55]
Train step of epoch 0:  40%|████      | 100/250 [01:36<02:22,  1.05it/s, loss=0.55]
Train step of epoch 0:  40%|████      | 100/250 [01:36<02:22,  1.05it/s, loss=0.691]
Train step of epoch 0:  40%|████      | 101/250 [01:37<02:21,  1.05it/s, loss=0.691]
Train step of epoch 0:  40%|████      | 101/250 [01:37<02:21,  1.05it/s, loss=0.68]
Train step of epoch 0:  41%|████      | 102/250 [01:38<02:20,  1.05it/s, loss=0.68]
Train step of epoch 0:  41%|████      | 102/250 [01:38<02:20,  1.05it/s, loss=0.681]
Train step of epoch 0:  41%|████      | 103/250 [01:39<02:19,  1.05it/s, loss=0.681]
Train step of epoch 0:  41%|████      | 103/250 [01:39<02:19,  1.05it/s, loss=0.695]
Train step of epoch 0:  42%|████▏     | 104/250 [01:40<02:19,  1.05it/s, loss=0.695]
Train step of epoch 0:  42%|████▏     | 104/250 [01:40<02:19,  1.05it/s, loss=0.733]
Train step of epoch 0:  42%|████▏     | 105/250 [01:41<02:18,  1.05it/s, loss=0.733]
Train step of epoch 0:  42%|████▏     | 105/250 [01:41<02:18,  1.05it/s, loss=0.659]
Train step of epoch 0:  42%|████▏     | 106/250 [01:42<02:17,  1.05it/s, loss=0.659]
Train step of epoch 0:  42%|████▏     | 106/250 [01:42<02:17,  1.05it/s, loss=0.653]
Train step of epoch 0:  43%|████▎     | 107/250 [01:43<02:17,  1.04it/s, loss=0.653]
Train step of epoch 0:  43%|████▎     | 107/250 [01:43<02:17,  1.04it/s, loss=0.741]
Train step of epoch 0:  43%|████▎     | 108/250 [01:44<02:15,  1.04it/s, loss=0.741]
Train step of epoch 0:  43%|████▎     | 108/250 [01:44<02:15,  1.04it/s, loss=0.599]
Train step of epoch 0:  44%|████▎     | 109/250 [01:45<02:14,  1.05it/s, loss=0.599]
Train step of epoch 0:  44%|████▎     | 109/250 [01:45<02:14,  1.05it/s, loss=0.673]
Train step of epoch 0:  44%|████▍     | 110/250 [01:46<02:13,  1.05it/s, loss=0.673]
Train step of epoch 0:  44%|████▍     | 110/250 [01:46<02:13,  1.05it/s, loss=0.734]
Train step of epoch 0:  44%|████▍     | 111/250 [01:47<02:12,  1.05it/s, loss=0.734]
Train step of epoch 0:  44%|████▍     | 111/250 [01:47<02:12,  1.05it/s, loss=0.624]
Train step of epoch 0:  45%|████▍     | 112/250 [01:48<02:11,  1.05it/s, loss=0.624]
Train step of epoch 0:  45%|████▍     | 112/250 [01:48<02:11,  1.05it/s, loss=0.657]
Train step of epoch 0:  45%|████▌     | 113/250 [01:49<02:10,  1.05it/s, loss=0.657]
Train step of epoch 0:  45%|████▌     | 113/250 [01:49<02:10,  1.05it/s, loss=0.677]
Train step of epoch 0:  46%|████▌     | 114/250 [01:50<02:10,  1.05it/s, loss=0.677]
Train step of epoch 0:  46%|████▌     | 114/250 [01:50<02:10,  1.05it/s, loss=0.842]
Train step of epoch 0:  46%|████▌     | 115/250 [01:51<02:09,  1.05it/s, loss=0.842]
Train step of epoch 0:  46%|████▌     | 115/250 [01:51<02:09,  1.05it/s, loss=0.683]
Train step of epoch 0:  46%|████▋     | 116/250 [01:52<02:08,  1.04it/s, loss=0.683]
Train step of epoch 0:  46%|████▋     | 116/250 [01:52<02:08,  1.04it/s, loss=0.593]
Train step of epoch 0:  47%|████▋     | 117/250 [01:52<02:07,  1.04it/s, loss=0.593]
Train step of epoch 0:  47%|████▋     | 117/250 [01:52<02:07,  1.04it/s, loss=0.575]
Train step of epoch 0:  47%|████▋     | 118/250 [01:53<02:06,  1.04it/s, loss=0.575]
Train step of epoch 0:  47%|████▋     | 118/250 [01:53<02:06,  1.04it/s, loss=0.543]
Train step of epoch 0:  48%|████▊     | 119/250 [01:54<02:05,  1.04it/s, loss=0.543]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

In [50]:
def inference_RM(input_text):
    input_ids = tokenizer.encode(input_text, return_tensors='pt').cuda()
    output = model(input_ids)
    output_reward = output.cpu().detach().numpy()[0]

    print('input: %s\nreward score: %.1f'%(input_text, output_reward))

    return output_reward

input_text = '인공지능은 똥멍청이 입니다'
output_reward = inference_RM(input_text=input_text)

input: 인공지능은 똥멍청이 입니다
reward score: -1.9

In [51]:
input_text = '인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.'

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다.
reward score: -1.7

In [52]:
input_text = "인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능(AI)은 컴퓨터에서 음성 및 작성된 언어를 보고 이해하고 번역하고 데이터를 분석하고 추천하는 기능을 포함하여 다양한 고급 기능을 수행할 수 있는 일련의 기술입니다. AI는 현대적인 컴퓨팅 혁신에서 중추적인 역할을 하며 개인과 비즈니스의 가치를 창출합니다. 예를 들어 광학 문자 인식(OCR)은 AI를 사용해 이미지 및 문서에서 텍스트 및 데이터를 추출하고, 구조화되지 않은 콘텐츠를 비즈니스에 바로 사용할 수 있게 만들고, 유용한 정보를 창출합니다.
reward score: -1.4

In [53]:
input_text = "인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다."

output_reward = inference_RM(input_text=input_text)

input: 인공지능은 일반적으로 인간의 지능이 필요하거나 인간이 분석할 수 있는 것보다 규모가 큰 데이터를 포함하는 방식으로 추론, 학습 및 행동할 수 있는 컴퓨터 및 기계를 구축하는 것과 관련된 과학 분야입니다. AI는 컴퓨터 공학, 데이터 분석 및 통계, 하드웨어 및 소프트웨어 엔지니어링, 언어학, 신경 과학은 물론 철학과 심리학을 포함하여 여러 학문을 포괄하는 광범위한 분야입니다. 비즈니스의 운영 수준에서 AI는 주로 머신러닝과 딥 러닝을 기반으로 하는 기술 모음으로, 데이터 분석, 예상 및 예측, 객체 분류, 자연어 처리, 추천, 지능형 데이터 가져오기 등을 수행할 수 있습니다.
reward score: -1.1

In [54]:
torch.cuda.empty_cache()

### SFT vs RM 비교 평가

In [55]:
# ── SFT vs RM: 정성 평가 + Reward Score 비교 ────────────────────────────
device = "cuda" if torch.cuda.is_available() else "cpu"

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}

eval_prompts_rm = [
    '인공지능(AI)은 무엇인가요?',
    '딥러닝과 머신러닝의 차이를 설명해줘.',
    '한국의 수도는 어디인가요?',
]

# SFT 모델로 답변 생성
sft_gen_local = transformers.pipeline(
    'text-generation',
    model=cfg.output_dir_SFT,
    tokenizer=PreTrainedTokenizerFast.from_pretrained(
        cfg.model_name,
        bos_token=cfg.bos_token, eos_token=cfg.eos_token,
        unk_token=cfg.unk_token, pad_token=cfg.pad_token,
    ),
    device=0 if torch.cuda.is_available() else -1,
)

gen_kw = dict(max_new_tokens=64, do_sample=True, top_k=50,
              repetition_penalty=2.0, no_repeat_ngram_size=4,
              eos_token_id=cfg.gen_eos_token_id, early_stopping=True)

def get_rm_score(rm_model, tokenizer, text):
    input_ids = tokenizer.encode(text, return_tensors='pt',
                                 truncation=True, max_length=256).to(device)
    with torch.no_grad():
        score = rm_model(input_ids)
    return score.cpu().item()

print("=" * 80)
print("[정성+RM점수 평가] SFT 모델 생성 답변의 RM 보상 점수")
print("=" * 80)
results = []
for raw_p in eval_prompts_rm:
    p = PROMPT_DICT['prompt_input'].format_map({'prompt': raw_p})
    sft_text = sft_gen_local(p, **gen_kw)[0]['generated_text']
    sft_ans  = sft_text[len(p):].strip()
    rm_s     = get_rm_score(model, tokenizer, p + sft_ans)
    results.append({'prompt': raw_p, 'sft_answer': sft_ans[:100], 'rm_score': round(rm_s, 4)})
    print(f"\n[PROMPT] {raw_p}")
    print(f"  [SFT 답변] {sft_ans[:120]}")
    print(f"  [RM 점수]  {rm_s:.4f}")

import pandas as pd
df_rm_eval = pd.DataFrame(results)
print("\n[RM 점수 요약]")
print(df_rm_eval[['prompt','rm_score']].to_string(index=False))

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The following generation flags are not valid and may be ignored: ['early_stopping']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Passing `generation_config` together with generation-related arguments=({'top_k', 'max_new_tokens', 'early_stopping', 'do_sample', 'eos_token_id', 'no_repeat_ngram_size', 'repetition_penalty'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
[정성+RM점수 평가] SFT 모델 생성 답변의 RM 보상 점수
================================================================================

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 인공지능(AI)은 무엇인가요?
  [SFT 답변] '저는 인공 지능 AI는 존재하지 않습니다. 인간의 뇌는 인간과 동일한 기능을 가지고 있지만, 다른 사람의 명령에 따라 행동하고 있습니다. 따라서 인간이 명령을 내리지 않거나 이행하지 않을 수 있다는 뜻입니다.提督,
  [RM 점수]  -1.8840

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 딥러닝과 머신러닝의 차이를 설명해줘.
  [SFT 답변] '1. AI: 인간의 경험은 인공지능이 개발해낸 것으로, 인간과 다르게 이해할 수 있습니다.\n2. 컴퓨터 모델에서 작동하는 데이터는 인간보다 훨씬 정확합니다. 하지만 이러한 차이는 인간이 학습한 데이터를 기반으로
  [RM 점수]  -1.9826

[PROMPT] 한국의 수도는 어디인가요?
  [SFT 답변] '한국 수도권에 위치한 서울시 종로구 종로3가 41번지입니다.辛世應(李)으로 불리며, 대한민국 서울특별시로 불리고 있습니다. 현재는 경복궁으로 사용되고 있으며, 주변에 한국민속촌, 한글관, 남산타워, 명소 등을 포함
  [RM 점수]  -2.0876

[RM 점수 요약]
              prompt  rm_score
    인공지능(AI)은 무엇인가요?   -1.8840
딥러닝과 머신러닝의 차이를 설명해줘.   -1.9826
      한국의 수도는 어디인가요?   -2.0876

## 5. Proximal Policy Optimization (PPO)

In [56]:
with NaiveStrategy().model_init_context():
    actor  = GPTActor(pretrained=cfg.output_dir_SFT, lora_rank=0).to(torch.cuda.current_device())
    critic = GPTCritic(pretrained=cfg.output_dir_RM,  lora_rank=0).to(torch.cuda.current_device())
    tokenizer = PreTrainedTokenizerFast.from_pretrained(
        cfg.model_name,
        bos_token=cfg.bos_token, eos_token=cfg.eos_token,
        unk_token=cfg.unk_token, pad_token=cfg.pad_token,
        padding_side=cfg.padding_side,
        model_max_length=cfg.model_max_length,
    )
    initial_model = deepcopy(actor)
    reward_model  = RewardModel(deepcopy(critic.model), deepcopy(critic.value_head)).to(torch.cuda.current_device())

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

In [57]:
actor_optim  = torch.optim.Adam(actor.parameters(),  lr=cfg.ppo_actor_lr)
critic_optim = torch.optim.Adam(critic.parameters(), lr=cfg.ppo_critic_lr)

In [58]:
(actor, actor_optim), (critic, critic_optim), reward_model, initial_model = NaiveStrategy().prepare(
    (actor, actor_optim), (critic, critic_optim), reward_model, initial_model)

In [59]:
with open(cfg.data_path_3_PPO, "r", encoding='utf-8-sig') as json_file:
    list_data_dict = json.load(json_file)
    list_prompt = [tmp['prompt'] for tmp in list_data_dict]

def tokenize_fn(texts):
    batch = tokenizer(
        texts,
        return_tensors='pt',
        max_length=cfg.ppo_tokenize_max_length,
        padding=True,
        truncation=True,
    )
    return {k: v.cuda() for k, v in batch.items()}

In [62]:
trainer = PPOTrainer(
    NaiveStrategy(),
    actor,
    critic,
    reward_model,
    initial_model,
    actor_optim,
    critic_optim,
    max_epochs=cfg.ppo_max_epochs,
    train_batch_size=cfg.ppo_train_batch_size,
    tokenizer=tokenize_fn,
    max_length=cfg.ppo_max_length,
    do_sample=True,
    temperature=cfg.ppo_temperature,
    top_k=cfg.ppo_top_k,
    pad_token_id=tokenizer.pad_token_id,
    eos_token_id=tokenizer.eos_token_id,
)

In [63]:
trainer.fit(
    list_prompt,
    num_episodes=cfg.ppo_num_episodes,
    max_timesteps=cfg.ppo_max_timesteps,
    update_timesteps=cfg.ppo_update_timesteps,
)
actor.model.save_pretrained(cfg.output_dir_PPO)

Episode [1/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.81s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0, critic_loss=0.000558]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.51it/s, actor_loss=0, critic_loss=0.000558]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.51it/s, actor_loss=0, critic_loss=0.144]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.62it/s, actor_loss=0, critic_loss=0.144]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.62it/s, actor_loss=0, critic_loss=0.0138]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.63it/s, actor_loss=0, critic_loss=0.0138]
Episode [1/10]: 100%|██████████| 3/3 [00:22<00:00,  7.41s/it]
Episode [2/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.88s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.163, critic_loss=0.0271]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.69it/s, actor_loss=0.163, critic_loss=0.0271]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.69it/s, actor_loss=0.17, critic_loss=0.0802]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.17, critic_loss=0.0802]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.167, critic_loss=0.0675]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.70it/s, actor_loss=0.167, critic_loss=0.0675]
Episode [2/10]: 100%|██████████| 3/3 [00:22<00:00,  7.45s/it]
Episode [3/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.82s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.162, critic_loss=0.0262]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.72it/s, actor_loss=0.162, critic_loss=0.0262]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.72it/s, actor_loss=0.146, critic_loss=0.000551]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.72it/s, actor_loss=0.146, critic_loss=0.000551]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.72it/s, actor_loss=0.143, critic_loss=0.0139]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.71it/s, actor_loss=0.143, critic_loss=0.0139]
Episode [3/10]: 100%|██████████| 3/3 [00:22<00:00,  7.37s/it]
Episode [4/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.73s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.178, critic_loss=0.0384]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.73it/s, actor_loss=-0.178, critic_loss=0.0384]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.73it/s, actor_loss=-0.177, critic_loss=0.0366]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.72it/s, actor_loss=-0.177, critic_loss=0.0366]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.72it/s, actor_loss=-0.177, critic_loss=0.0223]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.71it/s, actor_loss=-0.177, critic_loss=0.0223]
Episode [4/10]: 100%|██████████| 3/3 [00:21<00:00,  7.28s/it]
Episode [5/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.64s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0706, critic_loss=0.00658]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.70it/s, actor_loss=-0.0706, critic_loss=0.00658]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.70it/s, actor_loss=-0.0841, critic_loss=0.000276]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=-0.0841, critic_loss=0.000276]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=-0.0781, critic_loss=0.00884]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.71it/s, actor_loss=-0.0781, critic_loss=0.00884]
Episode [5/10]: 100%|██████████| 3/3 [00:21<00:00,  7.29s/it]
Episode [6/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.71s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.122, critic_loss=0.0172]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.71it/s, actor_loss=0.122, critic_loss=0.0172]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.71it/s, actor_loss=0.135, critic_loss=0.0244]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=0.135, critic_loss=0.0244]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=0.128, critic_loss=0.0144]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.71it/s, actor_loss=0.128, critic_loss=0.0144]
Episode [6/10]: 100%|██████████| 3/3 [00:21<00:00,  7.33s/it]
Episode [7/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.70s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.072, critic_loss=0.00662]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.71it/s, actor_loss=0.072, critic_loss=0.00662]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.71it/s, actor_loss=0.0589, critic_loss=0.0026]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.0589, critic_loss=0.0026]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.0388, critic_loss=0.00914]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.71it/s, actor_loss=0.0388, critic_loss=0.00914]
Episode [7/10]: 100%|██████████| 3/3 [00:21<00:00,  7.32s/it]
Episode [8/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.66s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0831, critic_loss=0.00735]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.70it/s, actor_loss=-0.0831, critic_loss=0.00735]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.70it/s, actor_loss=-0.0787, critic_loss=0.00695]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=-0.0787, critic_loss=0.00695]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=-0.0929, critic_loss=0.0115]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.70it/s, actor_loss=-0.0929, critic_loss=0.0115]
Episode [8/10]: 100%|██████████| 3/3 [00:21<00:00,  7.25s/it]
Episode [9/10]:  67%|██████▋   | 2/3 [00:12<00:05,  5.96s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=-0.0589, critic_loss=0.00372]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.71it/s, actor_loss=-0.0589, critic_loss=0.00372]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.71it/s, actor_loss=-0.0614, critic_loss=0.000584]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=-0.0614, critic_loss=0.000584]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.71it/s, actor_loss=-0.0587, critic_loss=0.00112]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.69it/s, actor_loss=-0.0587, critic_loss=0.00112]
Episode [9/10]: 100%|██████████| 3/3 [00:20<00:00,  6.83s/it]
Episode [10/10]:  67%|██████▋   | 2/3 [00:13<00:06,  6.69s/it]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s]
Train epoch [1/1]:   0%|          | 0/3 [00:00<?, ?it/s, actor_loss=0.0481, critic_loss=0.00304]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:00<00:01,  1.72it/s, actor_loss=0.0481, critic_loss=0.00304]
Train epoch [1/1]:  33%|███▎      | 1/3 [00:01<00:01,  1.72it/s, actor_loss=0.0594, critic_loss=0.0072]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.0594, critic_loss=0.0072]
Train epoch [1/1]:  67%|██████▋   | 2/3 [00:01<00:00,  1.70it/s, actor_loss=0.0409, critic_loss=0.00545]
Train epoch [1/1]: 100%|██████████| 3/3 [00:01<00:00,  1.69it/s, actor_loss=0.0409, critic_loss=0.00545]
Episode [10/10]: 100%|██████████| 3/3 [00:20<00:00,  6.70s/it]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

## 6. 최종 모델 비교

In [64]:
# ── Base / SFT / PPO 모델 로드 ──────────────────────────────────────────
tok = PreTrainedTokenizerFast.from_pretrained(
    cfg.model_name,
    bos_token=cfg.bos_token, eos_token=cfg.eos_token,
    unk_token=cfg.unk_token, pad_token=cfg.pad_token,
)

_pipe_kwargs = dict(tokenizer=tok, device=0 if torch.cuda.is_available() else -1)

base_pipe = transformers.pipeline('text-generation', model=cfg.model_name,     **_pipe_kwargs)
sft_pipe  = transformers.pipeline('text-generation', model=cfg.output_dir_SFT, **_pipe_kwargs)
ppo_pipe  = transformers.pipeline('text-generation', model=cfg.output_dir_PPO, **_pipe_kwargs)

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}

final_test_prompts = [
    '불고기용 고기 한우에요?',
    '리처드 닉슨이 43대 부통령직을 수행한 년도는?',
    '시카고 오헤어 국제공항은 어디에 있어?',
    '인공지능이 미래 사회에 미치는 영향은 무엇인가?',
    '지구 온난화의 주요 원인은 무엇인가?',
]

gen_kw_final = dict(
    max_new_tokens=cfg.gen_max_new_tokens,
    do_sample=True,
    top_k=cfg.gen_top_k,
    num_beams=cfg.gen_num_beams,
    repetition_penalty=cfg.gen_repetition_penalty,
    no_repeat_ngram_size=cfg.gen_no_repeat_ngram_size,
    eos_token_id=cfg.gen_eos_token_id,
    early_stopping=True,
)

print("=" * 80)
print("[정성 평가] Base KoGPT2 vs SFT vs PPO 최종 비교")
print("=" * 80)
for raw_p in final_test_prompts:
    p = PROMPT_DICT['prompt_input'].format_map({'prompt': raw_p})
    b = base_pipe(p, **gen_kw_final)[0]['generated_text'][len(p):]
    s = sft_pipe(p,  **gen_kw_final)[0]['generated_text'][len(p):]
    o = ppo_pipe(p,  **gen_kw_final)[0]['generated_text'][len(p):]
    print(f"\n[PROMPT] {raw_p}")
    print(f"  [Base] {b.strip()[:120]}")
    print(f"  [SFT]  {s.strip()[:120]}")
    print(f"  [PPO]  {o.strip()[:120]}")

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
[정성 평가] Base KoGPT2 vs SFT vs PPO 최종 비교
================================================================================

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 불고기용 고기 한우에요?
  [Base] #selfie #delicious #morning #instafood #foodstagram #소통 #맞팔 #선팔 #일상 #데일리 #먹방 #먹스타그램 #푸드
  [SFT]  '저는 인공지능 어시스턴트이기 때문에 고기를 먹을 수 없습니다. 하지만 일반적으로 불고기용 고기는 보통 돼지고기, 소고기, 닭고기 등 다양한 요리에 사용됩니다. 따라서 어떤 종류의 고기를 원하시는지 알려주시면 더 정
  [PPO]  '저는 인공지능 어시스턴트이기 때문에 고기를 먹을 수 없습니다. 하지만 일반적으로 불고기용 고기는 소고기, 돼지고기, 닭고기 등 다양한 요리에 사용됩니다. 따라서 해당 음식점에서 직접 확인해보시는 것을 추천드립니다.

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 리처드 닉슨이 43대 부통령직을 수행한 년도는?
  [Base]
  [SFT]  '리처드 닉슨은 47대 부통령직을 수행했습니다. 그는 1949년부터 1961년까지 부통령직을 수행하였습니다. 그는 1952년부터 1964년까지 부통령직을 맡았습니다. 그는 1954년부터 1963년까지 부통령직을 맡았
  [PPO]  '리처드 닉슨은 41대 부통령직을 수행했습니다. J.R. 롤링스톤 (John Rollington)입니다. J.R.롤링스톤은 1952년부터 1970년까지 부통령직을 수행하였습니다. J.Rollington은 1951년부

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 시카고 오헤어 국제공항은 어디에 있어?
  [Base] #selfie #daily #instagood #ootd #like4like #fff #f4f #l4l #lfl #follow #love #good #
  [SFT]  '저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고는 미국 캘리포니아주 로스앤젤레스(LA) 지역에 위치해 있습니다.證據, physical responses of this
  [PPO]  '저는 인공지능 어시스턴트이기 때문에 시카고에 대한 정보를 가지고 있지 않습니다. 하지만 시카고는 미국 캘리포니아주 로스앤젤레스(LA) 지역에 위치해 있습니다. 시카고는 미국에서 가장 큰 도시 중 하나입니다. 시카고

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 인공지능이 미래 사회에 미치는 영향은 무엇인가?
  [Base]
  [SFT]  '인공지능은 미래 사회에 미치는 영향을 예측하고 예측하는 능력을 가지고 있습니다. 인공지능은 인간의 행동과 감정을 예측하고 예측할 수 있는 능력을 가지고 있습니다. 이러한 능력은 인문학, 사회과학, 예술 등 다양한
  [PPO]  '인공지능의 미래 사회에 미치는 영향으로는 다음과 같은 것들이 있을 수 있습니다.\n\n1. 인공지능 기술의 발전: 인공지능 기술은 인간의 삶을 더욱 풍요롭게 만들어줍니다. 이를 통해 인간 삶의 질이 향상되고, 더

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 지구 온난화의 주요 원인은 무엇인가?
  [Base]
  [SFT]  '저는 인공지능 어시스턴트이기 때문에 지구 온난화에 대한 구체적인 정보를 가지고 있지 않습니다. 하지만 지구 온난화는 지구 온난화와 밀접한 관련이 있습니다. 지구 온난화는 기후 변화로 인해 발생하는 것으로 알려져 있
  [PPO]  '저는 인공지능 어시스턴트이기 때문에 지구 온난화에 대한 정확한 답변을 제공할 수 없습니다. 하지만 일반적으로 지구 온난화는 기후 변화로 인해 발생하는 것으로 알려져 있습니다. 지구 온난화는 지구 온난화를 유발하는

In [65]:
# ── 정량 평가: BLEU / ROUGE / Perplexity (Base vs SFT vs PPO) ───────────
import evaluate, json, random, torch
import pandas as pd
from transformers import AutoModelForCausalLM, PreTrainedTokenizerFast

bleu_m  = evaluate.load("bleu")
rouge_m = evaluate.load("rouge")

# 평가 데이터 샘플
import os
sft_eval_path = (cfg.data_path_1_SFT_clean
                 if os.path.exists(cfg.data_path_1_SFT_clean)
                 else cfg.data_path_1_SFT)
with open(sft_eval_path, 'r', encoding='utf-8-sig') as f:
    eval_data = json.load(f)
random.seed(42)
sample = random.sample(eval_data, min(100, len(eval_data)))

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}
prompts_q   = [PROMPT_DICT['prompt_input'].format_map({'prompt': d['prompt']}) for d in sample]
refs_text_q = [d['completion'] for d in sample]
refs_bleu_q = [[r] for r in refs_text_q]

gen_kw_q = dict(max_new_tokens=64, do_sample=False, num_beams=4,
                repetition_penalty=2.0, no_repeat_ngram_size=4,
                eos_token_id=cfg.gen_eos_token_id, early_stopping=True)

def gen_list_q(pipe, prompts):
    outs = []
    for i in range(0, len(prompts), 8):
        batch = pipe(prompts[i:i+8], **gen_kw_q)
        for j, res in enumerate(batch):
            text = res[0]['generated_text']
            outs.append(text[len(prompts[i+j]):].strip())
    return outs

print("Base 생성 중...")
base_preds_q = gen_list_q(base_pipe, prompts_q)
print("SFT 생성 중...")
sft_preds_q  = gen_list_q(sft_pipe,  prompts_q)
print("PPO 생성 중...")
ppo_preds_q  = gen_list_q(ppo_pipe,  prompts_q)

def safe_bleu(preds, refs):
    return bleu_m.compute(predictions=preds, references=refs)['bleu']

def safe_rouge(preds, refs):
    return rouge_m.compute(predictions=preds, references=refs)['rougeL']

# Perplexity
def calc_ppl(model_path, texts):
    tok = PreTrainedTokenizerFast.from_pretrained(cfg.model_name)
    if tok.pad_token is None: tok.pad_token = tok.eos_token
    mdl = AutoModelForCausalLM.from_pretrained(model_path).to(device)
    mdl.eval()
    ppls = []
    for t in texts[:20]:
        enc = tok(t, return_tensors='pt', truncation=True, max_length=256).to(device)
        with torch.no_grad():
            loss = mdl(**enc, labels=enc['input_ids']).loss
        ppls.append(torch.exp(loss).item())
    del mdl; torch.cuda.empty_cache()
    return sum(ppls)/len(ppls)

print("PPL 계산 중...")
ppl_b = calc_ppl(cfg.model_name,   refs_text_q)
ppl_s = calc_ppl(cfg.output_dir_SFT, refs_text_q)
ppl_p = calc_ppl(cfg.output_dir_PPO, refs_text_q)

df_final = pd.DataFrame({
    'Model':        ['Base KoGPT2', 'SFT', 'PPO'],
    'BLEU':         [round(safe_bleu(base_preds_q, refs_bleu_q), 4),
                     round(safe_bleu(sft_preds_q,  refs_bleu_q), 4),
                     round(safe_bleu(ppo_preds_q,  refs_bleu_q), 4)],
    'ROUGE-L':      [round(safe_rouge(base_preds_q, refs_text_q), 4),
                     round(safe_rouge(sft_preds_q,  refs_text_q), 4),
                     round(safe_rouge(ppo_preds_q,  refs_text_q), 4)],
    'Perplexity ↓': [round(ppl_b,2), round(ppl_s,2), round(ppl_p,2)],
})

print("\n[최종 정량 평가 결과] Base vs SFT vs PPO")
print(df_final.to_string(index=False))

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Base 생성 중...

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

SFT 생성 중...

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

PPO 생성 중...

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

PPL 계산 중...

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: skt/kogpt2-base-v2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

[최종 정량 평가 결과] Base vs SFT vs PPO
      Model   BLEU  ROUGE-L  Perplexity ↓
Base KoGPT2 0.0000   0.0005        350.48
        SFT 0.0329   0.0607        459.91
        PPO 0.0343   0.0384        480.15

In [66]:
# ── RM 점수 비교: SFT vs PPO ────────────────────────────────────────────
import torch

def rm_score_final(text):
    input_ids = tokenizer.encode(text, return_tensors='pt',
                                 truncation=True, max_length=256).cuda()
    with torch.no_grad():
        score = reward_model(input_ids)
    return score.cpu().item()

PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}

score_prompts = [
    '인공지능이 사회에 미치는 영향은?',
    '딥러닝과 머신러닝의 차이를 설명해줘.',
    '지구 온난화의 주요 원인은 무엇인가?',
]

gen_kw_rm = dict(max_new_tokens=64, do_sample=True, top_k=50,
                 repetition_penalty=2.0, no_repeat_ngram_size=4,
                 eos_token_id=cfg.gen_eos_token_id, early_stopping=True)

rows_rm = []
print("[RM 점수 비교] SFT vs PPO")
for raw_p in score_prompts:
    p = PROMPT_DICT['prompt_input'].format_map({'prompt': raw_p})
    sft_ans = sft_pipe(p, **gen_kw_rm)[0]['generated_text'][len(p):]
    ppo_ans = ppo_pipe(p, **gen_kw_rm)[0]['generated_text'][len(p):]
    sft_score = rm_score_final(p + sft_ans)
    ppo_score = rm_score_final(p + ppo_ans)
    rows_rm.append({'prompt': raw_p, 'sft_rm_score': round(sft_score,4),
                    'ppo_rm_score': round(ppo_score,4)})
    print(f"\n[PROMPT] {raw_p}")
    print(f"  SFT RM score: {sft_score:.4f}  |  PPO RM score: {ppo_score:.4f}")

import pandas as pd
df_rm_compare = pd.DataFrame(rows_rm)
print("\n[RM 점수 요약 테이블]")
print(df_rm_compare.to_string(index=False))

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[RM 점수 비교] SFT vs PPO

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 인공지능이 사회에 미치는 영향은?
  SFT RM score: -0.3458  |  PPO RM score: -0.3491

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 딥러닝과 머신러닝의 차이를 설명해줘.
  SFT RM score: -0.3411  |  PPO RM score: -0.3337

Both `max_new_tokens` (=64) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[PROMPT] 지구 온난화의 주요 원인은 무엇인가?
  SFT RM score: -0.3723  |  PPO RM score: -0.3652

[RM 점수 요약 테이블]
              prompt  sft_rm_score  ppo_rm_score
  인공지능이 사회에 미치는 영향은?       -0.3458       -0.3491
딥러닝과 머신러닝의 차이를 설명해줘.       -0.3411       -0.3337
지구 온난화의 주요 원인은 무엇인가?       -0.3723       -0.3652

### Generation 전략 실험

In [67]:
# ── 디코딩 전략 실험 ────────────────────────────────────────────────────
PROMPT_DICT = {"prompt_input": "### Instruction(명령어):\n{prompt}\n\n### Response(응답):"}
test_p = PROMPT_DICT['prompt_input'].format_map({'prompt': '인공지능이 미래 사회에 미치는 영향은?'})

strategies = {
    "Greedy":         dict(max_new_tokens=80, do_sample=False),
    "Beam-4":         dict(max_new_tokens=80, do_sample=False, num_beams=4,
                           no_repeat_ngram_size=4, repetition_penalty=2.0,
                           eos_token_id=cfg.gen_eos_token_id, early_stopping=True),
    "Top-k(k=50)":    dict(max_new_tokens=80, do_sample=True, top_k=50),
    "Top-p(p=0.9)":   dict(max_new_tokens=80, do_sample=True, top_p=0.9),
    "Beam+Top-k":     dict(max_new_tokens=80, do_sample=True, num_beams=4,
                           top_k=50, repetition_penalty=2.0,
                           no_repeat_ngram_size=4, early_stopping=True),
}

print("=" * 80)
print("[생성 전략 비교] PPO 모델 기준")
print("=" * 80)
rows_strat = []
for name, kw in strategies.items():
    out = ppo_pipe(test_p, **kw)[0]['generated_text'][len(test_p):]
    rows_strat.append({'strategy': name, 'output': out.strip()[:150]})
    print(f"\n[{name}]\n{out.strip()[:200]}")

df_strategies = pd.DataFrame(rows_strat)

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=80) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

================================================================================
[생성 전략 비교] PPO 모델 기준
================================================================================

Both `max_new_tokens` (=80) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Greedy]
'인공지능이 미래 사회에 미치는 영향은 다양합니다. 예를 들어, 인공지능은 인간의 지능과 관련된 다양한 문제를 해결하고 해결책을 제시할 수 있습니다. 이러한 문제들은 인간의 성장과 발전에 큰 영향을 미칩니다. 이러한 문제들은 인간의 성장과 발전에 큰 영향을 미칩니다. 이러한 문제들은 인간의 성장과 발전에 큰 영향을 미칩니다.

Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'top_k'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=80) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Beam-4]
'인공지능은 미래에 발생할 수 있는 여러 가지 요인에 의해 영향을 받는다고 알려져 있습니다. 예를 들어, 인공지능은 인간, 동물, 식물, 미생물 등 다양한 요인에 의해 영향을 받습니다. 이러한 요인들은 인간의 삶에서 중요한 요소 중 하나이기 때문에, 인간과 동물 모두에게 큰 영향을 미칠 수 있습니다. 또한, 인공지능 기술은 인간의 삶에 대한 이해와 이해를

Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'do_sample', 'top_p'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=80) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Top-k(k=50)]
'인공지능은 미래에 발생할 수 있는 문제에 대한 예측능력, 정보 접근성, 보안 등 다양한 분야에서 영향을 미치며, 모든 인간의 삶에 영향을 미치는 것은 아니므로, 이에 대한 정확한 예측은 가능하지 않습니다. 하지만, 인공지능이 미래에 발생하는 문제와 관련된 예측 능력을 발전시키기 위해서는 인간의 지식과 경험, 그리고 사회적 역할에 대한 이해와 노력이 필요합

Passing `generation_config` together with generation-related arguments=({'top_k', 'max_new_tokens', 'num_beams', 'early_stopping', 'do_sample', 'no_repeat_ngram_size', 'repetition_penalty'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=80) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[Top-p(p=0.9)]
'인공지능은 미래 사회의 변화를 선도하고 사회의 발전과 발전에 큰 역할을 합니다. 또한, 인간의 성장과 발전에 영향을 미치는 중요한 요소 중 하나입니다. 이러한 변화는 인간 개개인의 성장과 발전을 촉진하는 역할을 합니다. 따라서 인공지능은 인간의 성장과 발전에 큰 역할을 합니다. 따라서 인공지능은 인간의 성장과 발전을 촉진하는 역할을 합니다.

[Beam+Top-k]
'저는 인공지능 어시스턴트이기 때문에 인공지능이 미래에 미치는 영향을 알 수 없습니다. 하지만, 인공지능은 인간의 창의성과 문제해결 능력을 높이는 데 큰 역할을 합니다.